// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/coco/v1/coco.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/coco-sandbox/coco/pkg/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "coco.v1.AuthService"
	// GatewayServiceName is the fully-qualified name of the GatewayService service.
	GatewayServiceName = "coco.v1.GatewayService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceCreateAPIKeyProcedure is the fully-qualified name of the AuthService's CreateAPIKey
	// RPC.
	AuthServiceCreateAPIKeyProcedure = "/coco.v1.AuthService/CreateAPIKey"
	// AuthServiceListAPIKeysProcedure is the fully-qualified name of the AuthService's ListAPIKeys RPC.
	AuthServiceListAPIKeysProcedure = "/coco.v1.AuthService/ListAPIKeys"
	// AuthServiceDeleteAPIKeyProcedure is the fully-qualified name of the AuthService's DeleteAPIKey
	// RPC.
	AuthServiceDeleteAPIKeyProcedure = "/coco.v1.AuthService/DeleteAPIKey"
	// AuthServiceValidateAPIKeyProcedure is the fully-qualified name of the AuthService's
	// ValidateAPIKey RPC.
	AuthServiceValidateAPIKeyProcedure = "/coco.v1.AuthService/ValidateAPIKey"
	// GatewayServiceCreateSandboxProcedure is the fully-qualified name of the GatewayService's
	// CreateSandbox RPC.
	GatewayServiceCreateSandboxProcedure = "/coco.v1.GatewayService/CreateSandbox"
	// GatewayServiceGetSandboxProcedure is the fully-qualified name of the GatewayService's GetSandbox
	// RPC.
	GatewayServiceGetSandboxProcedure = "/coco.v1.GatewayService/GetSandbox"
	// GatewayServiceListSandboxesProcedure is the fully-qualified name of the GatewayService's
	// ListSandboxes RPC.
	GatewayServiceListSandboxesProcedure = "/coco.v1.GatewayService/ListSandboxes"
	// GatewayServiceDeleteSandboxProcedure is the fully-qualified name of the GatewayService's
	// DeleteSandbox RPC.
	GatewayServiceDeleteSandboxProcedure = "/coco.v1.GatewayService/DeleteSandbox"
	// GatewayServicePauseSandboxProcedure is the fully-qualified name of the GatewayService's
	// PauseSandbox RPC.
	GatewayServicePauseSandboxProcedure = "/coco.v1.GatewayService/PauseSandbox"
	// GatewayServiceResumeSandboxProcedure is the fully-qualified name of the GatewayService's
	// ResumeSandbox RPC.
	GatewayServiceResumeSandboxProcedure = "/coco.v1.GatewayService/ResumeSandbox"
	// GatewayServiceForkSandboxProcedure is the fully-qualified name of the GatewayService's
	// ForkSandbox RPC.
	GatewayServiceForkSandboxProcedure = "/coco.v1.GatewayService/ForkSandbox"
	// GatewayServiceHibernateSandboxProcedure is the fully-qualified name of the GatewayService's
	// HibernateSandbox RPC.
	GatewayServiceHibernateSandboxProcedure = "/coco.v1.GatewayService/HibernateSandbox"
	// GatewayServiceRestoreSandboxProcedure is the fully-qualified name of the GatewayService's
	// RestoreSandbox RPC.
	GatewayServiceRestoreSandboxProcedure = "/coco.v1.GatewayService/RestoreSandbox"
	// GatewayServiceExecProcedure is the fully-qualified name of the GatewayService's Exec RPC.
	GatewayServiceExecProcedure = "/coco.v1.GatewayService/Exec"
	// GatewayServiceStreamingExecProcedure is the fully-qualified name of the GatewayService's
	// StreamingExec RPC.
	GatewayServiceStreamingExecProcedure = "/coco.v1.GatewayService/StreamingExec"
	// GatewayServiceInteractiveExecProcedure is the fully-qualified name of the GatewayService's
	// InteractiveExec RPC.
	GatewayServiceInteractiveExecProcedure = "/coco.v1.GatewayService/InteractiveExec"
	// GatewayServiceCreateTemplateProcedure is the fully-qualified name of the GatewayService's
	// CreateTemplate RPC.
	GatewayServiceCreateTemplateProcedure = "/coco.v1.GatewayService/CreateTemplate"
	// GatewayServiceGetTemplateProcedure is the fully-qualified name of the GatewayService's
	// GetTemplate RPC.
	GatewayServiceGetTemplateProcedure = "/coco.v1.GatewayService/GetTemplate"
	// GatewayServiceListTemplatesProcedure is the fully-qualified name of the GatewayService's
	// ListTemplates RPC.
	GatewayServiceListTemplatesProcedure = "/coco.v1.GatewayService/ListTemplates"
	// GatewayServiceDeleteTemplateProcedure is the fully-qualified name of the GatewayService's
	// DeleteTemplate RPC.
	GatewayServiceDeleteTemplateProcedure = "/coco.v1.GatewayService/DeleteTemplate"
	// GatewayServiceBuildTemplateProcedure is the fully-qualified name of the GatewayService's
	// BuildTemplate RPC.
	GatewayServiceBuildTemplateProcedure = "/coco.v1.GatewayService/BuildTemplate"
	// GatewayServiceCreateCheckpointProcedure is the fully-qualified name of the GatewayService's
	// CreateCheckpoint RPC.
	GatewayServiceCreateCheckpointProcedure = "/coco.v1.GatewayService/CreateCheckpoint"
	// GatewayServiceListCheckpointsProcedure is the fully-qualified name of the GatewayService's
	// ListCheckpoints RPC.
	GatewayServiceListCheckpointsProcedure = "/coco.v1.GatewayService/ListCheckpoints"
	// GatewayServiceGetCheckpointProcedure is the fully-qualified name of the GatewayService's
	// GetCheckpoint RPC.
	GatewayServiceGetCheckpointProcedure = "/coco.v1.GatewayService/GetCheckpoint"
	// GatewayServiceDeleteCheckpointProcedure is the fully-qualified name of the GatewayService's
	// DeleteCheckpoint RPC.
	GatewayServiceDeleteCheckpointProcedure = "/coco.v1.GatewayService/DeleteCheckpoint"
	// GatewayServiceGetClusterInfoProcedure is the fully-qualified name of the GatewayService's
	// GetClusterInfo RPC.
	GatewayServiceGetClusterInfoProcedure = "/coco.v1.GatewayService/GetClusterInfo"
	// GatewayServiceListNodesProcedure is the fully-qualified name of the GatewayService's ListNodes
	// RPC.
	GatewayServiceListNodesProcedure = "/coco.v1.GatewayService/ListNodes"
	// GatewayServiceGetNodeProcedure is the fully-qualified name of the GatewayService's GetNode RPC.
	GatewayServiceGetNodeProcedure = "/coco.v1.GatewayService/GetNode"
	// GatewayServiceDrainNodeProcedure is the fully-qualified name of the GatewayService's DrainNode
	// RPC.
	GatewayServiceDrainNodeProcedure = "/coco.v1.GatewayService/DrainNode"
)

// AuthServiceClient is a client for the coco.v1.AuthService service.
type AuthServiceClient interface {
	CreateAPIKey(context.Context, *connect.Request[v1.CreateAPIKeyRequest]) (*connect.Response[v1.CreateAPIKeyResponse], error)
	ListAPIKeys(context.Context, *connect.Request[v1.ListAPIKeysRequest]) (*connect.Response[v1.ListAPIKeysResponse], error)
	DeleteAPIKey(context.Context, *connect.Request[v1.DeleteAPIKeyRequest]) (*connect.Response[v1.DeleteAPIKeyResponse], error)
	ValidateAPIKey(context.Context, *connect.Request[v1.ValidateAPIKeyRequest]) (*connect.Response[v1.ValidateAPIKeyResponse], error)
}

// NewAuthServiceClient constructs a client for the coco.v1.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_proto_coco_v1_coco_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		createAPIKey: connect.NewClient[v1.CreateAPIKeyRequest, v1.CreateAPIKeyResponse](
			httpClient,
			baseURL+AuthServiceCreateAPIKeyProcedure,
			connect.WithSchema(authServiceMethods.ByName("CreateAPIKey")),
			connect.WithClientOptions(opts...),
		),
		listAPIKeys: connect.NewClient[v1.ListAPIKeysRequest, v1.ListAPIKeysResponse](
			httpClient,
			baseURL+AuthServiceListAPIKeysProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListAPIKeys")),
			connect.WithClientOptions(opts...),
		),
		deleteAPIKey: connect.NewClient[v1.DeleteAPIKeyRequest, v1.DeleteAPIKeyResponse](
			httpClient,
			baseURL+AuthServiceDeleteAPIKeyProcedure,
			connect.WithSchema(authServiceMethods.ByName("DeleteAPIKey")),
			connect.WithClientOptions(opts...),
		),
		validateAPIKey: connect.NewClient[v1.ValidateAPIKeyRequest, v1.ValidateAPIKeyResponse](
			httpClient,
			baseURL+AuthServiceValidateAPIKeyProcedure,
			connect.WithSchema(authServiceMethods.ByName("ValidateAPIKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	createAPIKey   *connect.Client[v1.CreateAPIKeyRequest, v1.CreateAPIKeyResponse]
	listAPIKeys    *connect.Client[v1.ListAPIKeysRequest, v1.ListAPIKeysResponse]
	deleteAPIKey   *connect.Client[v1.DeleteAPIKeyRequest, v1.DeleteAPIKeyResponse]
	validateAPIKey *connect.Client[v1.ValidateAPIKeyRequest, v1.ValidateAPIKeyResponse]
}

// CreateAPIKey calls coco.v1.AuthService.CreateAPIKey.
func (c *authServiceClient) CreateAPIKey(ctx context.Context, req *connect.Request[v1.CreateAPIKeyRequest]) (*connect.Response[v1.CreateAPIKeyResponse], error) {
	return c.createAPIKey.CallUnary(ctx, req)
}

// ListAPIKeys calls coco.v1.AuthService.ListAPIKeys.
func (c *authServiceClient) ListAPIKeys(ctx context.Context, req *connect.Request[v1.ListAPIKeysRequest]) (*connect.Response[v1.ListAPIKeysResponse], error) {
	return c.listAPIKeys.CallUnary(ctx, req)
}

// DeleteAPIKey calls coco.v1.AuthService.DeleteAPIKey.
func (c *authServiceClient) DeleteAPIKey(ctx context.Context, req *connect.Request[v1.DeleteAPIKeyRequest]) (*connect.Response[v1.DeleteAPIKeyResponse], error) {
	return c.deleteAPIKey.CallUnary(ctx, req)
}

// ValidateAPIKey calls coco.v1.AuthService.ValidateAPIKey.
func (c *authServiceClient) ValidateAPIKey(ctx context.Context, req *connect.Request[v1.ValidateAPIKeyRequest]) (*connect.Response[v1.ValidateAPIKeyResponse], error) {
	return c.validateAPIKey.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the coco.v1.AuthService service.
type AuthServiceHandler interface {
	CreateAPIKey(context.Context, *connect.Request[v1.CreateAPIKeyRequest]) (*connect.Response[v1.CreateAPIKeyResponse], error)
	ListAPIKeys(context.Context, *connect.Request[v1.ListAPIKeysRequest]) (*connect.Response[v1.ListAPIKeysResponse], error)
	DeleteAPIKey(context.Context, *connect.Request[v1.DeleteAPIKeyRequest]) (*connect.Response[v1.DeleteAPIKeyResponse], error)
	ValidateAPIKey(context.Context, *connect.Request[v1.ValidateAPIKeyRequest]) (*connect.Response[v1.ValidateAPIKeyResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_proto_coco_v1_coco_proto.Services().ByName("AuthService").Methods()
	authServiceCreateAPIKeyHandler := connect.NewUnaryHandler(
		AuthServiceCreateAPIKeyProcedure,
		svc.CreateAPIKey,
		connect.WithSchema(authServiceMethods.ByName("CreateAPIKey")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListAPIKeysHandler := connect.NewUnaryHandler(
		AuthServiceListAPIKeysProcedure,
		svc.ListAPIKeys,
		connect.WithSchema(authServiceMethods.ByName("ListAPIKeys")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceDeleteAPIKeyHandler := connect.NewUnaryHandler(
		AuthServiceDeleteAPIKeyProcedure,
		svc.DeleteAPIKey,
		connect.WithSchema(authServiceMethods.ByName("DeleteAPIKey")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceValidateAPIKeyHandler := connect.NewUnaryHandler(
		AuthServiceValidateAPIKeyProcedure,
		svc.ValidateAPIKey,
		connect.WithSchema(authServiceMethods.ByName("ValidateAPIKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/coco.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceCreateAPIKeyProcedure:
			authServiceCreateAPIKeyHandler.ServeHTTP(w, r)
		case AuthServiceListAPIKeysProcedure:
			authServiceListAPIKeysHandler.ServeHTTP(w, r)
		case AuthServiceDeleteAPIKeyProcedure:
			authServiceDeleteAPIKeyHandler.ServeHTTP(w, r)
		case AuthServiceValidateAPIKeyProcedure:
			authServiceValidateAPIKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) CreateAPIKey(context.Context, *connect.Request[v1.CreateAPIKeyRequest]) (*connect.Response[v1.CreateAPIKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.AuthService.CreateAPIKey is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListAPIKeys(context.Context, *connect.Request[v1.ListAPIKeysRequest]) (*connect.Response[v1.ListAPIKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.AuthService.ListAPIKeys is not implemented"))
}

func (UnimplementedAuthServiceHandler) DeleteAPIKey(context.Context, *connect.Request[v1.DeleteAPIKeyRequest]) (*connect.Response[v1.DeleteAPIKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.AuthService.DeleteAPIKey is not implemented"))
}

func (UnimplementedAuthServiceHandler) ValidateAPIKey(context.Context, *connect.Request[v1.ValidateAPIKeyRequest]) (*connect.Response[v1.ValidateAPIKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.AuthService.ValidateAPIKey is not implemented"))
}

// GatewayServiceClient is a client for the coco.v1.GatewayService service.
type GatewayServiceClient interface {
	// Sandbox lifecycle
	CreateSandbox(context.Context, *connect.Request[v1.CreateSandboxRequest]) (*connect.Response[v1.CreateSandboxResponse], error)
	GetSandbox(context.Context, *connect.Request[v1.GetSandboxRequest]) (*connect.Response[v1.GetSandboxResponse], error)
	ListSandboxes(context.Context, *connect.Request[v1.ListSandboxesRequest]) (*connect.Response[v1.ListSandboxesResponse], error)
	DeleteSandbox(context.Context, *connect.Request[v1.DeleteSandboxRequest]) (*connect.Response[v1.DeleteSandboxResponse], error)
	// Sandbox control
	PauseSandbox(context.Context, *connect.Request[v1.PauseSandboxRequest]) (*connect.Response[v1.PauseSandboxResponse], error)
	ResumeSandbox(context.Context, *connect.Request[v1.ResumeSandboxRequest]) (*connect.Response[v1.ResumeSandboxResponse], error)
	ForkSandbox(context.Context, *connect.Request[v1.ForkSandboxRequest]) (*connect.Response[v1.ForkSandboxResponse], error)
	HibernateSandbox(context.Context, *connect.Request[v1.HibernateSandboxRequest]) (*connect.Response[v1.HibernateSandboxResponse], error)
	RestoreSandbox(context.Context, *connect.Request[v1.RestoreSandboxRequest]) (*connect.Response[v1.RestoreSandboxResponse], error)
	// Execution (spec 2.2)
	Exec(context.Context, *connect.Request[v1.ExecRequest]) (*connect.Response[v1.ExecResponse], error)
	StreamingExec(context.Context, *connect.Request[v1.StreamingExecRequest]) (*connect.ServerStreamForClient[v1.ExecChunk], error)
	InteractiveExec(context.Context, *connect.Request[v1.InteractiveExecRequest]) (*connect.ServerStreamForClient[v1.ExecChunk], error)
	// Templates (spec 2.3)
	CreateTemplate(context.Context, *connect.Request[v1.CreateTemplateRequest]) (*connect.Response[v1.CreateTemplateResponse], error)
	GetTemplate(context.Context, *connect.Request[v1.GetTemplateRequest]) (*connect.Response[v1.GetTemplateResponse], error)
	ListTemplates(context.Context, *connect.Request[v1.ListTemplatesRequest]) (*connect.Response[v1.ListTemplatesResponse], error)
	DeleteTemplate(context.Context, *connect.Request[v1.DeleteTemplateRequest]) (*connect.Response[v1.DeleteTemplateResponse], error)
	BuildTemplate(context.Context, *connect.Request[v1.BuildTemplateRequest]) (*connect.Response[v1.BuildTemplateResponse], error)
	// Checkpoints
	CreateCheckpoint(context.Context, *connect.Request[v1.CreateCheckpointRequest]) (*connect.Response[v1.CreateCheckpointResponse], error)
	ListCheckpoints(context.Context, *connect.Request[v1.ListCheckpointsRequest]) (*connect.Response[v1.ListCheckpointsResponse], error)
	GetCheckpoint(context.Context, *connect.Request[v1.GetCheckpointRequest]) (*connect.Response[v1.GetCheckpointResponse], error)
	DeleteCheckpoint(context.Context, *connect.Request[v1.DeleteCheckpointRequest]) (*connect.Response[v1.DeleteCheckpointResponse], error)
	// Cluster (spec 2.4)
	GetClusterInfo(context.Context, *connect.Request[v1.GetClusterInfoRequest]) (*connect.Response[v1.GetClusterInfoResponse], error)
	ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error)
	GetNode(context.Context, *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error)
	DrainNode(context.Context, *connect.Request[v1.DrainNodeRequest]) (*connect.Response[v1.DrainNodeResponse], error)
}

// NewGatewayServiceClient constructs a client for the coco.v1.GatewayService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGatewayServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GatewayServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gatewayServiceMethods := v1.File_proto_coco_v1_coco_proto.Services().ByName("GatewayService").Methods()
	return &gatewayServiceClient{
		createSandbox: connect.NewClient[v1.CreateSandboxRequest, v1.CreateSandboxResponse](
			httpClient,
			baseURL+GatewayServiceCreateSandboxProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("CreateSandbox")),
			connect.WithClientOptions(opts...),
		),
		getSandbox: connect.NewClient[v1.GetSandboxRequest, v1.GetSandboxResponse](
			httpClient,
			baseURL+GatewayServiceGetSandboxProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("GetSandbox")),
			connect.WithClientOptions(opts...),
		),
		listSandboxes: connect.NewClient[v1.ListSandboxesRequest, v1.ListSandboxesResponse](
			httpClient,
			baseURL+GatewayServiceListSandboxesProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("ListSandboxes")),
			connect.WithClientOptions(opts...),
		),
		deleteSandbox: connect.NewClient[v1.DeleteSandboxRequest, v1.DeleteSandboxResponse](
			httpClient,
			baseURL+GatewayServiceDeleteSandboxProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("DeleteSandbox")),
			connect.WithClientOptions(opts...),
		),
		pauseSandbox: connect.NewClient[v1.PauseSandboxRequest, v1.PauseSandboxResponse](
			httpClient,
			baseURL+GatewayServicePauseSandboxProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("PauseSandbox")),
			connect.WithClientOptions(opts...),
		),
		resumeSandbox: connect.NewClient[v1.ResumeSandboxRequest, v1.ResumeSandboxResponse](
			httpClient,
			baseURL+GatewayServiceResumeSandboxProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("ResumeSandbox")),
			connect.WithClientOptions(opts...),
		),
		forkSandbox: connect.NewClient[v1.ForkSandboxRequest, v1.ForkSandboxResponse](
			httpClient,
			baseURL+GatewayServiceForkSandboxProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("ForkSandbox")),
			connect.WithClientOptions(opts...),
		),
		hibernateSandbox: connect.NewClient[v1.HibernateSandboxRequest, v1.HibernateSandboxResponse](
			httpClient,
			baseURL+GatewayServiceHibernateSandboxProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("HibernateSandbox")),
			connect.WithClientOptions(opts...),
		),
		restoreSandbox: connect.NewClient[v1.RestoreSandboxRequest, v1.RestoreSandboxResponse](
			httpClient,
			baseURL+GatewayServiceRestoreSandboxProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("RestoreSandbox")),
			connect.WithClientOptions(opts...),
		),
		exec: connect.NewClient[v1.ExecRequest, v1.ExecResponse](
			httpClient,
			baseURL+GatewayServiceExecProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("Exec")),
			connect.WithClientOptions(opts...),
		),
		streamingExec: connect.NewClient[v1.StreamingExecRequest, v1.ExecChunk](
			httpClient,
			baseURL+GatewayServiceStreamingExecProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("StreamingExec")),
			connect.WithClientOptions(opts...),
		),
		interactiveExec: connect.NewClient[v1.InteractiveExecRequest, v1.ExecChunk](
			httpClient,
			baseURL+GatewayServiceInteractiveExecProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("InteractiveExec")),
			connect.WithClientOptions(opts...),
		),
		createTemplate: connect.NewClient[v1.CreateTemplateRequest, v1.CreateTemplateResponse](
			httpClient,
			baseURL+GatewayServiceCreateTemplateProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("CreateTemplate")),
			connect.WithClientOptions(opts...),
		),
		getTemplate: connect.NewClient[v1.GetTemplateRequest, v1.GetTemplateResponse](
			httpClient,
			baseURL+GatewayServiceGetTemplateProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("GetTemplate")),
			connect.WithClientOptions(opts...),
		),
		listTemplates: connect.NewClient[v1.ListTemplatesRequest, v1.ListTemplatesResponse](
			httpClient,
			baseURL+GatewayServiceListTemplatesProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("ListTemplates")),
			connect.WithClientOptions(opts...),
		),
		deleteTemplate: connect.NewClient[v1.DeleteTemplateRequest, v1.DeleteTemplateResponse](
			httpClient,
			baseURL+GatewayServiceDeleteTemplateProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("DeleteTemplate")),
			connect.WithClientOptions(opts...),
		),
		buildTemplate: connect.NewClient[v1.BuildTemplateRequest, v1.BuildTemplateResponse](
			httpClient,
			baseURL+GatewayServiceBuildTemplateProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("BuildTemplate")),
			connect.WithClientOptions(opts...),
		),
		createCheckpoint: connect.NewClient[v1.CreateCheckpointRequest, v1.CreateCheckpointResponse](
			httpClient,
			baseURL+GatewayServiceCreateCheckpointProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("CreateCheckpoint")),
			connect.WithClientOptions(opts...),
		),
		listCheckpoints: connect.NewClient[v1.ListCheckpointsRequest, v1.ListCheckpointsResponse](
			httpClient,
			baseURL+GatewayServiceListCheckpointsProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("ListCheckpoints")),
			connect.WithClientOptions(opts...),
		),
		getCheckpoint: connect.NewClient[v1.GetCheckpointRequest, v1.GetCheckpointResponse](
			httpClient,
			baseURL+GatewayServiceGetCheckpointProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("GetCheckpoint")),
			connect.WithClientOptions(opts...),
		),
		deleteCheckpoint: connect.NewClient[v1.DeleteCheckpointRequest, v1.DeleteCheckpointResponse](
			httpClient,
			baseURL+GatewayServiceDeleteCheckpointProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("DeleteCheckpoint")),
			connect.WithClientOptions(opts...),
		),
		getClusterInfo: connect.NewClient[v1.GetClusterInfoRequest, v1.GetClusterInfoResponse](
			httpClient,
			baseURL+GatewayServiceGetClusterInfoProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("GetClusterInfo")),
			connect.WithClientOptions(opts...),
		),
		listNodes: connect.NewClient[v1.ListNodesRequest, v1.ListNodesResponse](
			httpClient,
			baseURL+GatewayServiceListNodesProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("ListNodes")),
			connect.WithClientOptions(opts...),
		),
		getNode: connect.NewClient[v1.GetNodeRequest, v1.GetNodeResponse](
			httpClient,
			baseURL+GatewayServiceGetNodeProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("GetNode")),
			connect.WithClientOptions(opts...),
		),
		drainNode: connect.NewClient[v1.DrainNodeRequest, v1.DrainNodeResponse](
			httpClient,
			baseURL+GatewayServiceDrainNodeProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("DrainNode")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gatewayServiceClient implements GatewayServiceClient.
type gatewayServiceClient struct {
	createSandbox    *connect.Client[v1.CreateSandboxRequest, v1.CreateSandboxResponse]
	getSandbox       *connect.Client[v1.GetSandboxRequest, v1.GetSandboxResponse]
	listSandboxes    *connect.Client[v1.ListSandboxesRequest, v1.ListSandboxesResponse]
	deleteSandbox    *connect.Client[v1.DeleteSandboxRequest, v1.DeleteSandboxResponse]
	pauseSandbox     *connect.Client[v1.PauseSandboxRequest, v1.PauseSandboxResponse]
	resumeSandbox    *connect.Client[v1.ResumeSandboxRequest, v1.ResumeSandboxResponse]
	forkSandbox      *connect.Client[v1.ForkSandboxRequest, v1.ForkSandboxResponse]
	hibernateSandbox *connect.Client[v1.HibernateSandboxRequest, v1.HibernateSandboxResponse]
	restoreSandbox   *connect.Client[v1.RestoreSandboxRequest, v1.RestoreSandboxResponse]
	exec             *connect.Client[v1.ExecRequest, v1.ExecResponse]
	streamingExec    *connect.Client[v1.StreamingExecRequest, v1.ExecChunk]
	interactiveExec  *connect.Client[v1.InteractiveExecRequest, v1.ExecChunk]
	createTemplate   *connect.Client[v1.CreateTemplateRequest, v1.CreateTemplateResponse]
	getTemplate      *connect.Client[v1.GetTemplateRequest, v1.GetTemplateResponse]
	listTemplates    *connect.Client[v1.ListTemplatesRequest, v1.ListTemplatesResponse]
	deleteTemplate   *connect.Client[v1.DeleteTemplateRequest, v1.DeleteTemplateResponse]
	buildTemplate    *connect.Client[v1.BuildTemplateRequest, v1.BuildTemplateResponse]
	createCheckpoint *connect.Client[v1.CreateCheckpointRequest, v1.CreateCheckpointResponse]
	listCheckpoints  *connect.Client[v1.ListCheckpointsRequest, v1.ListCheckpointsResponse]
	getCheckpoint    *connect.Client[v1.GetCheckpointRequest, v1.GetCheckpointResponse]
	deleteCheckpoint *connect.Client[v1.DeleteCheckpointRequest, v1.DeleteCheckpointResponse]
	getClusterInfo   *connect.Client[v1.GetClusterInfoRequest, v1.GetClusterInfoResponse]
	listNodes        *connect.Client[v1.ListNodesRequest, v1.ListNodesResponse]
	getNode          *connect.Client[v1.GetNodeRequest, v1.GetNodeResponse]
	drainNode        *connect.Client[v1.DrainNodeRequest, v1.DrainNodeResponse]
}

// CreateSandbox calls coco.v1.GatewayService.CreateSandbox.
func (c *gatewayServiceClient) CreateSandbox(ctx context.Context, req *connect.Request[v1.CreateSandboxRequest]) (*connect.Response[v1.CreateSandboxResponse], error) {
	return c.createSandbox.CallUnary(ctx, req)
}

// GetSandbox calls coco.v1.GatewayService.GetSandbox.
func (c *gatewayServiceClient) GetSandbox(ctx context.Context, req *connect.Request[v1.GetSandboxRequest]) (*connect.Response[v1.GetSandboxResponse], error) {
	return c.getSandbox.CallUnary(ctx, req)
}

// ListSandboxes calls coco.v1.GatewayService.ListSandboxes.
func (c *gatewayServiceClient) ListSandboxes(ctx context.Context, req *connect.Request[v1.ListSandboxesRequest]) (*connect.Response[v1.ListSandboxesResponse], error) {
	return c.listSandboxes.CallUnary(ctx, req)
}

// DeleteSandbox calls coco.v1.GatewayService.DeleteSandbox.
func (c *gatewayServiceClient) DeleteSandbox(ctx context.Context, req *connect.Request[v1.DeleteSandboxRequest]) (*connect.Response[v1.DeleteSandboxResponse], error) {
	return c.deleteSandbox.CallUnary(ctx, req)
}

// PauseSandbox calls coco.v1.GatewayService.PauseSandbox.
func (c *gatewayServiceClient) PauseSandbox(ctx context.Context, req *connect.Request[v1.PauseSandboxRequest]) (*connect.Response[v1.PauseSandboxResponse], error) {
	return c.pauseSandbox.CallUnary(ctx, req)
}

// ResumeSandbox calls coco.v1.GatewayService.ResumeSandbox.
func (c *gatewayServiceClient) ResumeSandbox(ctx context.Context, req *connect.Request[v1.ResumeSandboxRequest]) (*connect.Response[v1.ResumeSandboxResponse], error) {
	return c.resumeSandbox.CallUnary(ctx, req)
}

// ForkSandbox calls coco.v1.GatewayService.ForkSandbox.
func (c *gatewayServiceClient) ForkSandbox(ctx context.Context, req *connect.Request[v1.ForkSandboxRequest]) (*connect.Response[v1.ForkSandboxResponse], error) {
	return c.forkSandbox.CallUnary(ctx, req)
}

// HibernateSandbox calls coco.v1.GatewayService.HibernateSandbox.
func (c *gatewayServiceClient) HibernateSandbox(ctx context.Context, req *connect.Request[v1.HibernateSandboxRequest]) (*connect.Response[v1.HibernateSandboxResponse], error) {
	return c.hibernateSandbox.CallUnary(ctx, req)
}

// RestoreSandbox calls coco.v1.GatewayService.RestoreSandbox.
func (c *gatewayServiceClient) RestoreSandbox(ctx context.Context, req *connect.Request[v1.RestoreSandboxRequest]) (*connect.Response[v1.RestoreSandboxResponse], error) {
	return c.restoreSandbox.CallUnary(ctx, req)
}

// Exec calls coco.v1.GatewayService.Exec.
func (c *gatewayServiceClient) Exec(ctx context.Context, req *connect.Request[v1.ExecRequest]) (*connect.Response[v1.ExecResponse], error) {
	return c.exec.CallUnary(ctx, req)
}

// StreamingExec calls coco.v1.GatewayService.StreamingExec.
func (c *gatewayServiceClient) StreamingExec(ctx context.Context, req *connect.Request[v1.StreamingExecRequest]) (*connect.ServerStreamForClient[v1.ExecChunk], error) {
	return c.streamingExec.CallServerStream(ctx, req)
}

// InteractiveExec calls coco.v1.GatewayService.InteractiveExec.
func (c *gatewayServiceClient) InteractiveExec(ctx context.Context, req *connect.Request[v1.InteractiveExecRequest]) (*connect.ServerStreamForClient[v1.ExecChunk], error) {
	return c.interactiveExec.CallServerStream(ctx, req)
}

// CreateTemplate calls coco.v1.GatewayService.CreateTemplate.
func (c *gatewayServiceClient) CreateTemplate(ctx context.Context, req *connect.Request[v1.CreateTemplateRequest]) (*connect.Response[v1.CreateTemplateResponse], error) {
	return c.createTemplate.CallUnary(ctx, req)
}

// GetTemplate calls coco.v1.GatewayService.GetTemplate.
func (c *gatewayServiceClient) GetTemplate(ctx context.Context, req *connect.Request[v1.GetTemplateRequest]) (*connect.Response[v1.GetTemplateResponse], error) {
	return c.getTemplate.CallUnary(ctx, req)
}

// ListTemplates calls coco.v1.GatewayService.ListTemplates.
func (c *gatewayServiceClient) ListTemplates(ctx context.Context, req *connect.Request[v1.ListTemplatesRequest]) (*connect.Response[v1.ListTemplatesResponse], error) {
	return c.listTemplates.CallUnary(ctx, req)
}

// DeleteTemplate calls coco.v1.GatewayService.DeleteTemplate.
func (c *gatewayServiceClient) DeleteTemplate(ctx context.Context, req *connect.Request[v1.DeleteTemplateRequest]) (*connect.Response[v1.DeleteTemplateResponse], error) {
	return c.deleteTemplate.CallUnary(ctx, req)
}

// BuildTemplate calls coco.v1.GatewayService.BuildTemplate.
func (c *gatewayServiceClient) BuildTemplate(ctx context.Context, req *connect.Request[v1.BuildTemplateRequest]) (*connect.Response[v1.BuildTemplateResponse], error) {
	return c.buildTemplate.CallUnary(ctx, req)
}

// CreateCheckpoint calls coco.v1.GatewayService.CreateCheckpoint.
func (c *gatewayServiceClient) CreateCheckpoint(ctx context.Context, req *connect.Request[v1.CreateCheckpointRequest]) (*connect.Response[v1.CreateCheckpointResponse], error) {
	return c.createCheckpoint.CallUnary(ctx, req)
}

// ListCheckpoints calls coco.v1.GatewayService.ListCheckpoints.
func (c *gatewayServiceClient) ListCheckpoints(ctx context.Context, req *connect.Request[v1.ListCheckpointsRequest]) (*connect.Response[v1.ListCheckpointsResponse], error) {
	return c.listCheckpoints.CallUnary(ctx, req)
}

// GetCheckpoint calls coco.v1.GatewayService.GetCheckpoint.
func (c *gatewayServiceClient) GetCheckpoint(ctx context.Context, req *connect.Request[v1.GetCheckpointRequest]) (*connect.Response[v1.GetCheckpointResponse], error) {
	return c.getCheckpoint.CallUnary(ctx, req)
}

// DeleteCheckpoint calls coco.v1.GatewayService.DeleteCheckpoint.
func (c *gatewayServiceClient) DeleteCheckpoint(ctx context.Context, req *connect.Request[v1.DeleteCheckpointRequest]) (*connect.Response[v1.DeleteCheckpointResponse], error) {
	return c.deleteCheckpoint.CallUnary(ctx, req)
}

// GetClusterInfo calls coco.v1.GatewayService.GetClusterInfo.
func (c *gatewayServiceClient) GetClusterInfo(ctx context.Context, req *connect.Request[v1.GetClusterInfoRequest]) (*connect.Response[v1.GetClusterInfoResponse], error) {
	return c.getClusterInfo.CallUnary(ctx, req)
}

// ListNodes calls coco.v1.GatewayService.ListNodes.
func (c *gatewayServiceClient) ListNodes(ctx context.Context, req *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error) {
	return c.listNodes.CallUnary(ctx, req)
}

// GetNode calls coco.v1.GatewayService.GetNode.
func (c *gatewayServiceClient) GetNode(ctx context.Context, req *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error) {
	return c.getNode.CallUnary(ctx, req)
}

// DrainNode calls coco.v1.GatewayService.DrainNode.
func (c *gatewayServiceClient) DrainNode(ctx context.Context, req *connect.Request[v1.DrainNodeRequest]) (*connect.Response[v1.DrainNodeResponse], error) {
	return c.drainNode.CallUnary(ctx, req)
}

// GatewayServiceHandler is an implementation of the coco.v1.GatewayService service.
type GatewayServiceHandler interface {
	// Sandbox lifecycle
	CreateSandbox(context.Context, *connect.Request[v1.CreateSandboxRequest]) (*connect.Response[v1.CreateSandboxResponse], error)
	GetSandbox(context.Context, *connect.Request[v1.GetSandboxRequest]) (*connect.Response[v1.GetSandboxResponse], error)
	ListSandboxes(context.Context, *connect.Request[v1.ListSandboxesRequest]) (*connect.Response[v1.ListSandboxesResponse], error)
	DeleteSandbox(context.Context, *connect.Request[v1.DeleteSandboxRequest]) (*connect.Response[v1.DeleteSandboxResponse], error)
	// Sandbox control
	PauseSandbox(context.Context, *connect.Request[v1.PauseSandboxRequest]) (*connect.Response[v1.PauseSandboxResponse], error)
	ResumeSandbox(context.Context, *connect.Request[v1.ResumeSandboxRequest]) (*connect.Response[v1.ResumeSandboxResponse], error)
	ForkSandbox(context.Context, *connect.Request[v1.ForkSandboxRequest]) (*connect.Response[v1.ForkSandboxResponse], error)
	HibernateSandbox(context.Context, *connect.Request[v1.HibernateSandboxRequest]) (*connect.Response[v1.HibernateSandboxResponse], error)
	RestoreSandbox(context.Context, *connect.Request[v1.RestoreSandboxRequest]) (*connect.Response[v1.RestoreSandboxResponse], error)
	// Execution (spec 2.2)
	Exec(context.Context, *connect.Request[v1.ExecRequest]) (*connect.Response[v1.ExecResponse], error)
	StreamingExec(context.Context, *connect.Request[v1.StreamingExecRequest], *connect.ServerStream[v1.ExecChunk]) error
	InteractiveExec(context.Context, *connect.Request[v1.InteractiveExecRequest], *connect.ServerStream[v1.ExecChunk]) error
	// Templates (spec 2.3)
	CreateTemplate(context.Context, *connect.Request[v1.CreateTemplateRequest]) (*connect.Response[v1.CreateTemplateResponse], error)
	GetTemplate(context.Context, *connect.Request[v1.GetTemplateRequest]) (*connect.Response[v1.GetTemplateResponse], error)
	ListTemplates(context.Context, *connect.Request[v1.ListTemplatesRequest]) (*connect.Response[v1.ListTemplatesResponse], error)
	DeleteTemplate(context.Context, *connect.Request[v1.DeleteTemplateRequest]) (*connect.Response[v1.DeleteTemplateResponse], error)
	BuildTemplate(context.Context, *connect.Request[v1.BuildTemplateRequest]) (*connect.Response[v1.BuildTemplateResponse], error)
	// Checkpoints
	CreateCheckpoint(context.Context, *connect.Request[v1.CreateCheckpointRequest]) (*connect.Response[v1.CreateCheckpointResponse], error)
	ListCheckpoints(context.Context, *connect.Request[v1.ListCheckpointsRequest]) (*connect.Response[v1.ListCheckpointsResponse], error)
	GetCheckpoint(context.Context, *connect.Request[v1.GetCheckpointRequest]) (*connect.Response[v1.GetCheckpointResponse], error)
	DeleteCheckpoint(context.Context, *connect.Request[v1.DeleteCheckpointRequest]) (*connect.Response[v1.DeleteCheckpointResponse], error)
	// Cluster (spec 2.4)
	GetClusterInfo(context.Context, *connect.Request[v1.GetClusterInfoRequest]) (*connect.Response[v1.GetClusterInfoResponse], error)
	ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error)
	GetNode(context.Context, *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error)
	DrainNode(context.Context, *connect.Request[v1.DrainNodeRequest]) (*connect.Response[v1.DrainNodeResponse], error)
}

// NewGatewayServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGatewayServiceHandler(svc GatewayServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gatewayServiceMethods := v1.File_proto_coco_v1_coco_proto.Services().ByName("GatewayService").Methods()
	gatewayServiceCreateSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceCreateSandboxProcedure,
		svc.CreateSandbox,
		connect.WithSchema(gatewayServiceMethods.ByName("CreateSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceGetSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceGetSandboxProcedure,
		svc.GetSandbox,
		connect.WithSchema(gatewayServiceMethods.ByName("GetSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceListSandboxesHandler := connect.NewUnaryHandler(
		GatewayServiceListSandboxesProcedure,
		svc.ListSandboxes,
		connect.WithSchema(gatewayServiceMethods.ByName("ListSandboxes")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceDeleteSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceDeleteSandboxProcedure,
		svc.DeleteSandbox,
		connect.WithSchema(gatewayServiceMethods.ByName("DeleteSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServicePauseSandboxHandler := connect.NewUnaryHandler(
		GatewayServicePauseSandboxProcedure,
		svc.PauseSandbox,
		connect.WithSchema(gatewayServiceMethods.ByName("PauseSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceResumeSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceResumeSandboxProcedure,
		svc.ResumeSandbox,
		connect.WithSchema(gatewayServiceMethods.ByName("ResumeSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceForkSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceForkSandboxProcedure,
		svc.ForkSandbox,
		connect.WithSchema(gatewayServiceMethods.ByName("ForkSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceHibernateSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceHibernateSandboxProcedure,
		svc.HibernateSandbox,
		connect.WithSchema(gatewayServiceMethods.ByName("HibernateSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceRestoreSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceRestoreSandboxProcedure,
		svc.RestoreSandbox,
		connect.WithSchema(gatewayServiceMethods.ByName("RestoreSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceExecHandler := connect.NewUnaryHandler(
		GatewayServiceExecProcedure,
		svc.Exec,
		connect.WithSchema(gatewayServiceMethods.ByName("Exec")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceStreamingExecHandler := connect.NewServerStreamHandler(
		GatewayServiceStreamingExecProcedure,
		svc.StreamingExec,
		connect.WithSchema(gatewayServiceMethods.ByName("StreamingExec")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceInteractiveExecHandler := connect.NewServerStreamHandler(
		GatewayServiceInteractiveExecProcedure,
		svc.InteractiveExec,
		connect.WithSchema(gatewayServiceMethods.ByName("InteractiveExec")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceCreateTemplateHandler := connect.NewUnaryHandler(
		GatewayServiceCreateTemplateProcedure,
		svc.CreateTemplate,
		connect.WithSchema(gatewayServiceMethods.ByName("CreateTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceGetTemplateHandler := connect.NewUnaryHandler(
		GatewayServiceGetTemplateProcedure,
		svc.GetTemplate,
		connect.WithSchema(gatewayServiceMethods.ByName("GetTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceListTemplatesHandler := connect.NewUnaryHandler(
		GatewayServiceListTemplatesProcedure,
		svc.ListTemplates,
		connect.WithSchema(gatewayServiceMethods.ByName("ListTemplates")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceDeleteTemplateHandler := connect.NewUnaryHandler(
		GatewayServiceDeleteTemplateProcedure,
		svc.DeleteTemplate,
		connect.WithSchema(gatewayServiceMethods.ByName("DeleteTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceBuildTemplateHandler := connect.NewUnaryHandler(
		GatewayServiceBuildTemplateProcedure,
		svc.BuildTemplate,
		connect.WithSchema(gatewayServiceMethods.ByName("BuildTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceCreateCheckpointHandler := connect.NewUnaryHandler(
		GatewayServiceCreateCheckpointProcedure,
		svc.CreateCheckpoint,
		connect.WithSchema(gatewayServiceMethods.ByName("CreateCheckpoint")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceListCheckpointsHandler := connect.NewUnaryHandler(
		GatewayServiceListCheckpointsProcedure,
		svc.ListCheckpoints,
		connect.WithSchema(gatewayServiceMethods.ByName("ListCheckpoints")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceGetCheckpointHandler := connect.NewUnaryHandler(
		GatewayServiceGetCheckpointProcedure,
		svc.GetCheckpoint,
		connect.WithSchema(gatewayServiceMethods.ByName("GetCheckpoint")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceDeleteCheckpointHandler := connect.NewUnaryHandler(
		GatewayServiceDeleteCheckpointProcedure,
		svc.DeleteCheckpoint,
		connect.WithSchema(gatewayServiceMethods.ByName("DeleteCheckpoint")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceGetClusterInfoHandler := connect.NewUnaryHandler(
		GatewayServiceGetClusterInfoProcedure,
		svc.GetClusterInfo,
		connect.WithSchema(gatewayServiceMethods.ByName("GetClusterInfo")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceListNodesHandler := connect.NewUnaryHandler(
		GatewayServiceListNodesProcedure,
		svc.ListNodes,
		connect.WithSchema(gatewayServiceMethods.ByName("ListNodes")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceGetNodeHandler := connect.NewUnaryHandler(
		GatewayServiceGetNodeProcedure,
		svc.GetNode,
		connect.WithSchema(gatewayServiceMethods.ByName("GetNode")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceDrainNodeHandler := connect.NewUnaryHandler(
		GatewayServiceDrainNodeProcedure,
		svc.DrainNode,
		connect.WithSchema(gatewayServiceMethods.ByName("DrainNode")),
		connect.WithHandlerOptions(opts...),
	)
	return "/coco.v1.GatewayService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GatewayServiceCreateSandboxProcedure:
			gatewayServiceCreateSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceGetSandboxProcedure:
			gatewayServiceGetSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceListSandboxesProcedure:
			gatewayServiceListSandboxesHandler.ServeHTTP(w, r)
		case GatewayServiceDeleteSandboxProcedure:
			gatewayServiceDeleteSandboxHandler.ServeHTTP(w, r)
		case GatewayServicePauseSandboxProcedure:
			gatewayServicePauseSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceResumeSandboxProcedure:
			gatewayServiceResumeSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceForkSandboxProcedure:
			gatewayServiceForkSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceHibernateSandboxProcedure:
			gatewayServiceHibernateSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceRestoreSandboxProcedure:
			gatewayServiceRestoreSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceExecProcedure:
			gatewayServiceExecHandler.ServeHTTP(w, r)
		case GatewayServiceStreamingExecProcedure:
			gatewayServiceStreamingExecHandler.ServeHTTP(w, r)
		case GatewayServiceInteractiveExecProcedure:
			gatewayServiceInteractiveExecHandler.ServeHTTP(w, r)
		case GatewayServiceCreateTemplateProcedure:
			gatewayServiceCreateTemplateHandler.ServeHTTP(w, r)
		case GatewayServiceGetTemplateProcedure:
			gatewayServiceGetTemplateHandler.ServeHTTP(w, r)
		case GatewayServiceListTemplatesProcedure:
			gatewayServiceListTemplatesHandler.ServeHTTP(w, r)
		case GatewayServiceDeleteTemplateProcedure:
			gatewayServiceDeleteTemplateHandler.ServeHTTP(w, r)
		case GatewayServiceBuildTemplateProcedure:
			gatewayServiceBuildTemplateHandler.ServeHTTP(w, r)
		case GatewayServiceCreateCheckpointProcedure:
			gatewayServiceCreateCheckpointHandler.ServeHTTP(w, r)
		case GatewayServiceListCheckpointsProcedure:
			gatewayServiceListCheckpointsHandler.ServeHTTP(w, r)
		case GatewayServiceGetCheckpointProcedure:
			gatewayServiceGetCheckpointHandler.ServeHTTP(w, r)
		case GatewayServiceDeleteCheckpointProcedure:
			gatewayServiceDeleteCheckpointHandler.ServeHTTP(w, r)
		case GatewayServiceGetClusterInfoProcedure:
			gatewayServiceGetClusterInfoHandler.ServeHTTP(w, r)
		case GatewayServiceListNodesProcedure:
			gatewayServiceListNodesHandler.ServeHTTP(w, r)
		case GatewayServiceGetNodeProcedure:
			gatewayServiceGetNodeHandler.ServeHTTP(w, r)
		case GatewayServiceDrainNodeProcedure:
			gatewayServiceDrainNodeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGatewayServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGatewayServiceHandler struct{}

func (UnimplementedGatewayServiceHandler) CreateSandbox(context.Context, *connect.Request[v1.CreateSandboxRequest]) (*connect.Response[v1.CreateSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.CreateSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) GetSandbox(context.Context, *connect.Request[v1.GetSandboxRequest]) (*connect.Response[v1.GetSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.GetSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ListSandboxes(context.Context, *connect.Request[v1.ListSandboxesRequest]) (*connect.Response[v1.ListSandboxesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.ListSandboxes is not implemented"))
}

func (UnimplementedGatewayServiceHandler) DeleteSandbox(context.Context, *connect.Request[v1.DeleteSandboxRequest]) (*connect.Response[v1.DeleteSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.DeleteSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) PauseSandbox(context.Context, *connect.Request[v1.PauseSandboxRequest]) (*connect.Response[v1.PauseSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.PauseSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ResumeSandbox(context.Context, *connect.Request[v1.ResumeSandboxRequest]) (*connect.Response[v1.ResumeSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.ResumeSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ForkSandbox(context.Context, *connect.Request[v1.ForkSandboxRequest]) (*connect.Response[v1.ForkSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.ForkSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) HibernateSandbox(context.Context, *connect.Request[v1.HibernateSandboxRequest]) (*connect.Response[v1.HibernateSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.HibernateSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) RestoreSandbox(context.Context, *connect.Request[v1.RestoreSandboxRequest]) (*connect.Response[v1.RestoreSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.RestoreSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) Exec(context.Context, *connect.Request[v1.ExecRequest]) (*connect.Response[v1.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.Exec is not implemented"))
}

func (UnimplementedGatewayServiceHandler) StreamingExec(context.Context, *connect.Request[v1.StreamingExecRequest], *connect.ServerStream[v1.ExecChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.StreamingExec is not implemented"))
}

func (UnimplementedGatewayServiceHandler) InteractiveExec(context.Context, *connect.Request[v1.InteractiveExecRequest], *connect.ServerStream[v1.ExecChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.InteractiveExec is not implemented"))
}

func (UnimplementedGatewayServiceHandler) CreateTemplate(context.Context, *connect.Request[v1.CreateTemplateRequest]) (*connect.Response[v1.CreateTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.CreateTemplate is not implemented"))
}

func (UnimplementedGatewayServiceHandler) GetTemplate(context.Context, *connect.Request[v1.GetTemplateRequest]) (*connect.Response[v1.GetTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.GetTemplate is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ListTemplates(context.Context, *connect.Request[v1.ListTemplatesRequest]) (*connect.Response[v1.ListTemplatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.ListTemplates is not implemented"))
}

func (UnimplementedGatewayServiceHandler) DeleteTemplate(context.Context, *connect.Request[v1.DeleteTemplateRequest]) (*connect.Response[v1.DeleteTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.DeleteTemplate is not implemented"))
}

func (UnimplementedGatewayServiceHandler) BuildTemplate(context.Context, *connect.Request[v1.BuildTemplateRequest]) (*connect.Response[v1.BuildTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.BuildTemplate is not implemented"))
}

func (UnimplementedGatewayServiceHandler) CreateCheckpoint(context.Context, *connect.Request[v1.CreateCheckpointRequest]) (*connect.Response[v1.CreateCheckpointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.CreateCheckpoint is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ListCheckpoints(context.Context, *connect.Request[v1.ListCheckpointsRequest]) (*connect.Response[v1.ListCheckpointsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.ListCheckpoints is not implemented"))
}

func (UnimplementedGatewayServiceHandler) GetCheckpoint(context.Context, *connect.Request[v1.GetCheckpointRequest]) (*connect.Response[v1.GetCheckpointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.GetCheckpoint is not implemented"))
}

func (UnimplementedGatewayServiceHandler) DeleteCheckpoint(context.Context, *connect.Request[v1.DeleteCheckpointRequest]) (*connect.Response[v1.DeleteCheckpointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.DeleteCheckpoint is not implemented"))
}

func (UnimplementedGatewayServiceHandler) GetClusterInfo(context.Context, *connect.Request[v1.GetClusterInfoRequest]) (*connect.Response[v1.GetClusterInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.GetClusterInfo is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.ListNodes is not implemented"))
}

func (UnimplementedGatewayServiceHandler) GetNode(context.Context, *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.GetNode is not implemented"))
}

func (UnimplementedGatewayServiceHandler) DrainNode(context.Context, *connect.Request[v1.DrainNodeRequest]) (*connect.Response[v1.DrainNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.DrainNode is not implemented"))
}
