// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tc_shaperShaperBucket struct {
	_              structs.HostLayout
	Tokens         uint64
	LastRefillNs   uint64
	RateBps        uint64
	BurstBytes     uint64
	PriorityWeight uint32
	Pad            uint32
}

// loadTc_shaper returns the embedded CollectionSpec for tc_shaper.
func loadTc_shaper() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Tc_shaperBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tc_shaper: %w", err)
	}

	return spec, err
}

// loadTc_shaperObjects loads tc_shaper and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tc_shaperObjects
//	*tc_shaperPrograms
//	*tc_shaperMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTc_shaperObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTc_shaper()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tc_shaperSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_shaperSpecs struct {
	tc_shaperProgramSpecs
	tc_shaperMapSpecs
	tc_shaperVariableSpecs
}

// tc_shaperProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_shaperProgramSpecs struct {
	TcShaper *ebpf.ProgramSpec `ebpf:"tc_shaper"`
}

// tc_shaperMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_shaperMapSpecs struct {
	CocoShaperBuckets *ebpf.MapSpec `ebpf:"coco_shaper_buckets"`
}

// tc_shaperVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_shaperVariableSpecs struct {
}

// tc_shaperObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTc_shaperObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_shaperObjects struct {
	tc_shaperPrograms
	tc_shaperMaps
	tc_shaperVariables
}

func (o *tc_shaperObjects) Close() error {
	return _Tc_shaperClose(
		&o.tc_shaperPrograms,
		&o.tc_shaperMaps,
	)
}

// tc_shaperMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTc_shaperObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_shaperMaps struct {
	CocoShaperBuckets *ebpf.Map `ebpf:"coco_shaper_buckets"`
}

func (m *tc_shaperMaps) Close() error {
	return _Tc_shaperClose(
		m.CocoShaperBuckets,
	)
}

// tc_shaperVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTc_shaperObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_shaperVariables struct {
}

// tc_shaperPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTc_shaperObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_shaperPrograms struct {
	TcShaper *ebpf.Program `ebpf:"tc_shaper"`
}

func (p *tc_shaperPrograms) Close() error {
	return _Tc_shaperClose(
		p.TcShaper,
	)
}

func _Tc_shaperClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tc_shaper_bpfel.o
var _Tc_shaperBytes []byte
