// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdp_fwdFlowKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	_        [3]byte
}

type xdp_fwdFlowValue struct {
	_        structs.HostLayout
	Packets  uint64
	Bytes    uint64
	VmId     uint32
	_        [4]byte
	LastSeen uint64
}

type xdp_fwdNatEntry struct {
	_            structs.HostLayout
	InternalIp   uint32
	ExternalIp   uint32
	InternalPort uint16
	ExternalPort uint16
	Protocol     uint8
	Active       uint8
	_            [2]byte
}

type xdp_fwdRateLimitBucket struct {
	_            structs.HostLayout
	Tokens       uint64
	LastRefillNs uint64
	RatePps      uint64
	BurstPackets uint64
}

type xdp_fwdVmInfo struct {
	_      structs.HostLayout
	VmId   uint32
	Mac    [6]uint8
	_      [2]byte
	IpAddr uint32
	Active uint8
	_      [3]byte
}

// loadXdp_fwd returns the embedded CollectionSpec for xdp_fwd.
func loadXdp_fwd() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Xdp_fwdBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp_fwd: %w", err)
	}

	return spec, err
}

// loadXdp_fwdObjects loads xdp_fwd and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdp_fwdObjects
//	*xdp_fwdPrograms
//	*xdp_fwdMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdp_fwdObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp_fwd()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdp_fwdSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_fwdSpecs struct {
	xdp_fwdProgramSpecs
	xdp_fwdMapSpecs
	xdp_fwdVariableSpecs
}

// xdp_fwdProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_fwdProgramSpecs struct {
	XdpFwdEgress  *ebpf.ProgramSpec `ebpf:"xdp_fwd_egress"`
	XdpFwdIngress *ebpf.ProgramSpec `ebpf:"xdp_fwd_ingress"`
	XdpFwdProg    *ebpf.ProgramSpec `ebpf:"xdp_fwd_prog"`
}

// xdp_fwdMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_fwdMapSpecs struct {
	CocoFlows      *ebpf.MapSpec `ebpf:"coco_flows"`
	CocoNat        *ebpf.MapSpec `ebpf:"coco_nat"`
	CocoRateLimits *ebpf.MapSpec `ebpf:"coco_rate_limits"`
	CocoStats      *ebpf.MapSpec `ebpf:"coco_stats"`
	CocoVms        *ebpf.MapSpec `ebpf:"coco_vms"`
}

// xdp_fwdVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_fwdVariableSpecs struct {
}

// xdp_fwdObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdp_fwdObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_fwdObjects struct {
	xdp_fwdPrograms
	xdp_fwdMaps
	xdp_fwdVariables
}

func (o *xdp_fwdObjects) Close() error {
	return _Xdp_fwdClose(
		&o.xdp_fwdPrograms,
		&o.xdp_fwdMaps,
	)
}

// xdp_fwdMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdp_fwdObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_fwdMaps struct {
	CocoFlows      *ebpf.Map `ebpf:"coco_flows"`
	CocoNat        *ebpf.Map `ebpf:"coco_nat"`
	CocoRateLimits *ebpf.Map `ebpf:"coco_rate_limits"`
	CocoStats      *ebpf.Map `ebpf:"coco_stats"`
	CocoVms        *ebpf.Map `ebpf:"coco_vms"`
}

func (m *xdp_fwdMaps) Close() error {
	return _Xdp_fwdClose(
		m.CocoFlows,
		m.CocoNat,
		m.CocoRateLimits,
		m.CocoStats,
		m.CocoVms,
	)
}

// xdp_fwdVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdp_fwdObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_fwdVariables struct {
}

// xdp_fwdPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdp_fwdObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_fwdPrograms struct {
	XdpFwdEgress  *ebpf.Program `ebpf:"xdp_fwd_egress"`
	XdpFwdIngress *ebpf.Program `ebpf:"xdp_fwd_ingress"`
	XdpFwdProg    *ebpf.Program `ebpf:"xdp_fwd_prog"`
}

func (p *xdp_fwdPrograms) Close() error {
	return _Xdp_fwdClose(
		p.XdpFwdEgress,
		p.XdpFwdIngress,
		p.XdpFwdProg,
	)
}

func _Xdp_fwdClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_fwd_bpfel.o
var _Xdp_fwdBytes []byte
