// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdp_filterFlowKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	_        [3]byte
}

type xdp_filterFlowValue struct {
	_        structs.HostLayout
	Packets  uint64
	Bytes    uint64
	VmId     uint32
	_        [4]byte
	LastSeen uint64
}

type xdp_filterNatEntry struct {
	_            structs.HostLayout
	InternalIp   uint32
	ExternalIp   uint32
	InternalPort uint16
	ExternalPort uint16
	Protocol     uint8
	Active       uint8
	_            [2]byte
}

type xdp_filterRateLimitBucket struct {
	_            structs.HostLayout
	Tokens       uint64
	LastRefillNs uint64
	RatePps      uint64
	BurstPackets uint64
}

type xdp_filterVmInfo struct {
	_      structs.HostLayout
	VmId   uint32
	Mac    [6]uint8
	_      [2]byte
	IpAddr uint32
	Active uint8
	_      [3]byte
}

// loadXdp_filter returns the embedded CollectionSpec for xdp_filter.
func loadXdp_filter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Xdp_filterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp_filter: %w", err)
	}

	return spec, err
}

// loadXdp_filterObjects loads xdp_filter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdp_filterObjects
//	*xdp_filterPrograms
//	*xdp_filterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdp_filterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp_filter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdp_filterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_filterSpecs struct {
	xdp_filterProgramSpecs
	xdp_filterMapSpecs
	xdp_filterVariableSpecs
}

// xdp_filterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_filterProgramSpecs struct {
	XdpFilterEgress  *ebpf.ProgramSpec `ebpf:"xdp_filter_egress"`
	XdpFilterIngress *ebpf.ProgramSpec `ebpf:"xdp_filter_ingress"`
	XdpFilterProg    *ebpf.ProgramSpec `ebpf:"xdp_filter_prog"`
}

// xdp_filterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_filterMapSpecs struct {
	CocoFlows      *ebpf.MapSpec `ebpf:"coco_flows"`
	CocoNat        *ebpf.MapSpec `ebpf:"coco_nat"`
	CocoRateLimits *ebpf.MapSpec `ebpf:"coco_rate_limits"`
	CocoStats      *ebpf.MapSpec `ebpf:"coco_stats"`
	CocoVms        *ebpf.MapSpec `ebpf:"coco_vms"`
}

// xdp_filterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_filterVariableSpecs struct {
}

// xdp_filterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdp_filterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_filterObjects struct {
	xdp_filterPrograms
	xdp_filterMaps
	xdp_filterVariables
}

func (o *xdp_filterObjects) Close() error {
	return _Xdp_filterClose(
		&o.xdp_filterPrograms,
		&o.xdp_filterMaps,
	)
}

// xdp_filterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdp_filterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_filterMaps struct {
	CocoFlows      *ebpf.Map `ebpf:"coco_flows"`
	CocoNat        *ebpf.Map `ebpf:"coco_nat"`
	CocoRateLimits *ebpf.Map `ebpf:"coco_rate_limits"`
	CocoStats      *ebpf.Map `ebpf:"coco_stats"`
	CocoVms        *ebpf.Map `ebpf:"coco_vms"`
}

func (m *xdp_filterMaps) Close() error {
	return _Xdp_filterClose(
		m.CocoFlows,
		m.CocoNat,
		m.CocoRateLimits,
		m.CocoStats,
		m.CocoVms,
	)
}

// xdp_filterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdp_filterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_filterVariables struct {
}

// xdp_filterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdp_filterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_filterPrograms struct {
	XdpFilterEgress  *ebpf.Program `ebpf:"xdp_filter_egress"`
	XdpFilterIngress *ebpf.Program `ebpf:"xdp_filter_ingress"`
	XdpFilterProg    *ebpf.Program `ebpf:"xdp_filter_prog"`
}

func (p *xdp_filterPrograms) Close() error {
	return _Xdp_filterClose(
		p.XdpFilterEgress,
		p.XdpFilterIngress,
		p.XdpFilterProg,
	)
}

func _Xdp_filterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_filter_bpfeb.o
var _Xdp_filterBytes []byte
