// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdp_statsFlowKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	_        [3]byte
}

type xdp_statsFlowValue struct {
	_        structs.HostLayout
	Packets  uint64
	Bytes    uint64
	VmId     uint32
	_        [4]byte
	LastSeen uint64
}

type xdp_statsNatEntry struct {
	_            structs.HostLayout
	InternalIp   uint32
	ExternalIp   uint32
	InternalPort uint16
	ExternalPort uint16
	Protocol     uint8
	Active       uint8
	_            [2]byte
}

type xdp_statsRateLimitBucket struct {
	_            structs.HostLayout
	Tokens       uint64
	LastRefillNs uint64
	RatePps      uint64
	BurstPackets uint64
}

type xdp_statsVmInfo struct {
	_      structs.HostLayout
	VmId   uint32
	Mac    [6]uint8
	_      [2]byte
	IpAddr uint32
	Active uint8
	_      [3]byte
}

// loadXdp_stats returns the embedded CollectionSpec for xdp_stats.
func loadXdp_stats() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Xdp_statsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp_stats: %w", err)
	}

	return spec, err
}

// loadXdp_statsObjects loads xdp_stats and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdp_statsObjects
//	*xdp_statsPrograms
//	*xdp_statsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdp_statsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp_stats()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdp_statsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_statsSpecs struct {
	xdp_statsProgramSpecs
	xdp_statsMapSpecs
	xdp_statsVariableSpecs
}

// xdp_statsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_statsProgramSpecs struct {
	XdpStatsEgress  *ebpf.ProgramSpec `ebpf:"xdp_stats_egress"`
	XdpStatsIngress *ebpf.ProgramSpec `ebpf:"xdp_stats_ingress"`
	XdpStatsProg    *ebpf.ProgramSpec `ebpf:"xdp_stats_prog"`
}

// xdp_statsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_statsMapSpecs struct {
	CocoFlows      *ebpf.MapSpec `ebpf:"coco_flows"`
	CocoNat        *ebpf.MapSpec `ebpf:"coco_nat"`
	CocoRateLimits *ebpf.MapSpec `ebpf:"coco_rate_limits"`
	CocoStats      *ebpf.MapSpec `ebpf:"coco_stats"`
	CocoVms        *ebpf.MapSpec `ebpf:"coco_vms"`
}

// xdp_statsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_statsVariableSpecs struct {
}

// xdp_statsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdp_statsObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_statsObjects struct {
	xdp_statsPrograms
	xdp_statsMaps
	xdp_statsVariables
}

func (o *xdp_statsObjects) Close() error {
	return _Xdp_statsClose(
		&o.xdp_statsPrograms,
		&o.xdp_statsMaps,
	)
}

// xdp_statsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdp_statsObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_statsMaps struct {
	CocoFlows      *ebpf.Map `ebpf:"coco_flows"`
	CocoNat        *ebpf.Map `ebpf:"coco_nat"`
	CocoRateLimits *ebpf.Map `ebpf:"coco_rate_limits"`
	CocoStats      *ebpf.Map `ebpf:"coco_stats"`
	CocoVms        *ebpf.Map `ebpf:"coco_vms"`
}

func (m *xdp_statsMaps) Close() error {
	return _Xdp_statsClose(
		m.CocoFlows,
		m.CocoNat,
		m.CocoRateLimits,
		m.CocoStats,
		m.CocoVms,
	)
}

// xdp_statsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdp_statsObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_statsVariables struct {
}

// xdp_statsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdp_statsObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_statsPrograms struct {
	XdpStatsEgress  *ebpf.Program `ebpf:"xdp_stats_egress"`
	XdpStatsIngress *ebpf.Program `ebpf:"xdp_stats_ingress"`
	XdpStatsProg    *ebpf.Program `ebpf:"xdp_stats_prog"`
}

func (p *xdp_statsPrograms) Close() error {
	return _Xdp_statsClose(
		p.XdpStatsEgress,
		p.XdpStatsIngress,
		p.XdpStatsProg,
	)
}

func _Xdp_statsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_stats_bpfel.o
var _Xdp_statsBytes []byte
