// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdp_conntrackFlowKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	_        [3]byte
}

type xdp_conntrackFlowValue struct {
	_        structs.HostLayout
	Packets  uint64
	Bytes    uint64
	VmId     uint32
	_        [4]byte
	LastSeen uint64
}

type xdp_conntrackNatEntry struct {
	_            structs.HostLayout
	InternalIp   uint32
	ExternalIp   uint32
	InternalPort uint16
	ExternalPort uint16
	Protocol     uint8
	Active       uint8
	_            [2]byte
}

type xdp_conntrackRateLimitBucket struct {
	_            structs.HostLayout
	Tokens       uint64
	LastRefillNs uint64
	RatePps      uint64
	BurstPackets uint64
}

type xdp_conntrackVmInfo struct {
	_      structs.HostLayout
	VmId   uint32
	Mac    [6]uint8
	_      [2]byte
	IpAddr uint32
	Active uint8
	_      [3]byte
}

// loadXdp_conntrack returns the embedded CollectionSpec for xdp_conntrack.
func loadXdp_conntrack() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Xdp_conntrackBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp_conntrack: %w", err)
	}

	return spec, err
}

// loadXdp_conntrackObjects loads xdp_conntrack and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdp_conntrackObjects
//	*xdp_conntrackPrograms
//	*xdp_conntrackMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdp_conntrackObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp_conntrack()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdp_conntrackSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_conntrackSpecs struct {
	xdp_conntrackProgramSpecs
	xdp_conntrackMapSpecs
	xdp_conntrackVariableSpecs
}

// xdp_conntrackProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_conntrackProgramSpecs struct {
	XdpConntrackEgress  *ebpf.ProgramSpec `ebpf:"xdp_conntrack_egress"`
	XdpConntrackIngress *ebpf.ProgramSpec `ebpf:"xdp_conntrack_ingress"`
	XdpConntrackProg    *ebpf.ProgramSpec `ebpf:"xdp_conntrack_prog"`
}

// xdp_conntrackMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_conntrackMapSpecs struct {
	CocoFlows      *ebpf.MapSpec `ebpf:"coco_flows"`
	CocoNat        *ebpf.MapSpec `ebpf:"coco_nat"`
	CocoRateLimits *ebpf.MapSpec `ebpf:"coco_rate_limits"`
	CocoStats      *ebpf.MapSpec `ebpf:"coco_stats"`
	CocoVms        *ebpf.MapSpec `ebpf:"coco_vms"`
}

// xdp_conntrackVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_conntrackVariableSpecs struct {
}

// xdp_conntrackObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdp_conntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_conntrackObjects struct {
	xdp_conntrackPrograms
	xdp_conntrackMaps
	xdp_conntrackVariables
}

func (o *xdp_conntrackObjects) Close() error {
	return _Xdp_conntrackClose(
		&o.xdp_conntrackPrograms,
		&o.xdp_conntrackMaps,
	)
}

// xdp_conntrackMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdp_conntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_conntrackMaps struct {
	CocoFlows      *ebpf.Map `ebpf:"coco_flows"`
	CocoNat        *ebpf.Map `ebpf:"coco_nat"`
	CocoRateLimits *ebpf.Map `ebpf:"coco_rate_limits"`
	CocoStats      *ebpf.Map `ebpf:"coco_stats"`
	CocoVms        *ebpf.Map `ebpf:"coco_vms"`
}

func (m *xdp_conntrackMaps) Close() error {
	return _Xdp_conntrackClose(
		m.CocoFlows,
		m.CocoNat,
		m.CocoRateLimits,
		m.CocoStats,
		m.CocoVms,
	)
}

// xdp_conntrackVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdp_conntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_conntrackVariables struct {
}

// xdp_conntrackPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdp_conntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_conntrackPrograms struct {
	XdpConntrackEgress  *ebpf.Program `ebpf:"xdp_conntrack_egress"`
	XdpConntrackIngress *ebpf.Program `ebpf:"xdp_conntrack_ingress"`
	XdpConntrackProg    *ebpf.Program `ebpf:"xdp_conntrack_prog"`
}

func (p *xdp_conntrackPrograms) Close() error {
	return _Xdp_conntrackClose(
		p.XdpConntrackEgress,
		p.XdpConntrackIngress,
		p.XdpConntrackProg,
	)
}

func _Xdp_conntrackClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_conntrack_bpfel.o
var _Xdp_conntrackBytes []byte
