// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdp_natFlowKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	_        [3]byte
}

type xdp_natFlowValue struct {
	_        structs.HostLayout
	Packets  uint64
	Bytes    uint64
	VmId     uint32
	_        [4]byte
	LastSeen uint64
}

type xdp_natNatEntry struct {
	_            structs.HostLayout
	InternalIp   uint32
	ExternalIp   uint32
	InternalPort uint16
	ExternalPort uint16
	Protocol     uint8
	Active       uint8
	_            [2]byte
}

type xdp_natRateLimitBucket struct {
	_            structs.HostLayout
	Tokens       uint64
	LastRefillNs uint64
	RatePps      uint64
	BurstPackets uint64
}

type xdp_natVmInfo struct {
	_      structs.HostLayout
	VmId   uint32
	Mac    [6]uint8
	_      [2]byte
	IpAddr uint32
	Active uint8
	_      [3]byte
}

// loadXdp_nat returns the embedded CollectionSpec for xdp_nat.
func loadXdp_nat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Xdp_natBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp_nat: %w", err)
	}

	return spec, err
}

// loadXdp_natObjects loads xdp_nat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdp_natObjects
//	*xdp_natPrograms
//	*xdp_natMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdp_natObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp_nat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdp_natSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_natSpecs struct {
	xdp_natProgramSpecs
	xdp_natMapSpecs
	xdp_natVariableSpecs
}

// xdp_natProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_natProgramSpecs struct {
	XdpNatIngress *ebpf.ProgramSpec `ebpf:"xdp_nat_ingress"`
	XdpNatProg    *ebpf.ProgramSpec `ebpf:"xdp_nat_prog"`
}

// xdp_natMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_natMapSpecs struct {
	CocoFlows      *ebpf.MapSpec `ebpf:"coco_flows"`
	CocoNat        *ebpf.MapSpec `ebpf:"coco_nat"`
	CocoRateLimits *ebpf.MapSpec `ebpf:"coco_rate_limits"`
	CocoStats      *ebpf.MapSpec `ebpf:"coco_stats"`
	CocoVms        *ebpf.MapSpec `ebpf:"coco_vms"`
}

// xdp_natVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_natVariableSpecs struct {
}

// xdp_natObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdp_natObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_natObjects struct {
	xdp_natPrograms
	xdp_natMaps
	xdp_natVariables
}

func (o *xdp_natObjects) Close() error {
	return _Xdp_natClose(
		&o.xdp_natPrograms,
		&o.xdp_natMaps,
	)
}

// xdp_natMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdp_natObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_natMaps struct {
	CocoFlows      *ebpf.Map `ebpf:"coco_flows"`
	CocoNat        *ebpf.Map `ebpf:"coco_nat"`
	CocoRateLimits *ebpf.Map `ebpf:"coco_rate_limits"`
	CocoStats      *ebpf.Map `ebpf:"coco_stats"`
	CocoVms        *ebpf.Map `ebpf:"coco_vms"`
}

func (m *xdp_natMaps) Close() error {
	return _Xdp_natClose(
		m.CocoFlows,
		m.CocoNat,
		m.CocoRateLimits,
		m.CocoStats,
		m.CocoVms,
	)
}

// xdp_natVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdp_natObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_natVariables struct {
}

// xdp_natPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdp_natObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_natPrograms struct {
	XdpNatIngress *ebpf.Program `ebpf:"xdp_nat_ingress"`
	XdpNatProg    *ebpf.Program `ebpf:"xdp_nat_prog"`
}

func (p *xdp_natPrograms) Close() error {
	return _Xdp_natClose(
		p.XdpNatIngress,
		p.XdpNatProg,
	)
}

func _Xdp_natClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_nat_bpfel.o
var _Xdp_natBytes []byte
