// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/coco/v1/checkpoint.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckpointCompression int32

const (
	CheckpointCompression_CHECKPOINT_COMPRESSION_UNSPECIFIED CheckpointCompression = 0
	CheckpointCompression_CHECKPOINT_COMPRESSION_NONE        CheckpointCompression = 1
	CheckpointCompression_CHECKPOINT_COMPRESSION_ZSTD        CheckpointCompression = 2
	CheckpointCompression_CHECKPOINT_COMPRESSION_LZ4         CheckpointCompression = 3
)

// Enum value maps for CheckpointCompression.
var (
	CheckpointCompression_name = map[int32]string{
		0: "CHECKPOINT_COMPRESSION_UNSPECIFIED",
		1: "CHECKPOINT_COMPRESSION_NONE",
		2: "CHECKPOINT_COMPRESSION_ZSTD",
		3: "CHECKPOINT_COMPRESSION_LZ4",
	}
	CheckpointCompression_value = map[string]int32{
		"CHECKPOINT_COMPRESSION_UNSPECIFIED": 0,
		"CHECKPOINT_COMPRESSION_NONE":        1,
		"CHECKPOINT_COMPRESSION_ZSTD":        2,
		"CHECKPOINT_COMPRESSION_LZ4":         3,
	}
)

func (x CheckpointCompression) Enum() *CheckpointCompression {
	p := new(CheckpointCompression)
	*p = x
	return p
}

func (x CheckpointCompression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointCompression) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_coco_v1_checkpoint_proto_enumTypes[0].Descriptor()
}

func (CheckpointCompression) Type() protoreflect.EnumType {
	return &file_proto_coco_v1_checkpoint_proto_enumTypes[0]
}

func (x CheckpointCompression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointCompression.Descriptor instead.
func (CheckpointCompression) EnumDescriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{0}
}

type CheckpointStage int32

const (
	CheckpointStage_CHECKPOINT_STAGE_UNSPECIFIED CheckpointStage = 0
	CheckpointStage_CHECKPOINT_STAGE_MEMORY      CheckpointStage = 1
	CheckpointStage_CHECKPOINT_STAGE_DISK        CheckpointStage = 2
	CheckpointStage_CHECKPOINT_STAGE_FINALIZING  CheckpointStage = 3
)

// Enum value maps for CheckpointStage.
var (
	CheckpointStage_name = map[int32]string{
		0: "CHECKPOINT_STAGE_UNSPECIFIED",
		1: "CHECKPOINT_STAGE_MEMORY",
		2: "CHECKPOINT_STAGE_DISK",
		3: "CHECKPOINT_STAGE_FINALIZING",
	}
	CheckpointStage_value = map[string]int32{
		"CHECKPOINT_STAGE_UNSPECIFIED": 0,
		"CHECKPOINT_STAGE_MEMORY":      1,
		"CHECKPOINT_STAGE_DISK":        2,
		"CHECKPOINT_STAGE_FINALIZING":  3,
	}
)

func (x CheckpointStage) Enum() *CheckpointStage {
	p := new(CheckpointStage)
	*p = x
	return p
}

func (x CheckpointStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointStage) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_coco_v1_checkpoint_proto_enumTypes[1].Descriptor()
}

func (CheckpointStage) Type() protoreflect.EnumType {
	return &file_proto_coco_v1_checkpoint_proto_enumTypes[1]
}

func (x CheckpointStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointStage.Descriptor instead.
func (CheckpointStage) EnumDescriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{1}
}

// Detailed checkpoint metadata (extends coco.Checkpoint)
type CheckpointDetail struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SandboxId          string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Path               string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	SizeBytes          int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	IsCompressed       bool                   `protobuf:"varint,6,opt,name=is_compressed,json=isCompressed,proto3" json:"is_compressed,omitempty"`
	Compression        CheckpointCompression  `protobuf:"varint,7,opt,name=compression,proto3,enum=coco.v1.CheckpointCompression" json:"compression,omitempty"`
	MemorySizeBytes    int64                  `protobuf:"varint,8,opt,name=memory_size_bytes,json=memorySizeBytes,proto3" json:"memory_size_bytes,omitempty"`
	DiskSizeBytes      int64                  `protobuf:"varint,9,opt,name=disk_size_bytes,json=diskSizeBytes,proto3" json:"disk_size_bytes,omitempty"`
	DurationMs         int64                  `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Incremental        bool                   `protobuf:"varint,11,opt,name=incremental,proto3" json:"incremental,omitempty"`
	ParentCheckpointId string                 `protobuf:"bytes,12,opt,name=parent_checkpoint_id,json=parentCheckpointId,proto3" json:"parent_checkpoint_id,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CheckpointDetail) Reset() {
	*x = CheckpointDetail{}
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointDetail) ProtoMessage() {}

func (x *CheckpointDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointDetail.ProtoReflect.Descriptor instead.
func (*CheckpointDetail) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{0}
}

func (x *CheckpointDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckpointDetail) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CheckpointDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckpointDetail) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CheckpointDetail) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CheckpointDetail) GetIsCompressed() bool {
	if x != nil {
		return x.IsCompressed
	}
	return false
}

func (x *CheckpointDetail) GetCompression() CheckpointCompression {
	if x != nil {
		return x.Compression
	}
	return CheckpointCompression_CHECKPOINT_COMPRESSION_UNSPECIFIED
}

func (x *CheckpointDetail) GetMemorySizeBytes() int64 {
	if x != nil {
		return x.MemorySizeBytes
	}
	return 0
}

func (x *CheckpointDetail) GetDiskSizeBytes() int64 {
	if x != nil {
		return x.DiskSizeBytes
	}
	return 0
}

func (x *CheckpointDetail) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CheckpointDetail) GetIncremental() bool {
	if x != nil {
		return x.Incremental
	}
	return false
}

func (x *CheckpointDetail) GetParentCheckpointId() string {
	if x != nil {
		return x.ParentCheckpointId
	}
	return ""
}

func (x *CheckpointDetail) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SandboxId        string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Compression      CheckpointCompression  `protobuf:"varint,3,opt,name=compression,proto3,enum=coco.v1.CheckpointCompression" json:"compression,omitempty"`
	Incremental      bool                   `protobuf:"varint,4,opt,name=incremental,proto3" json:"incremental,omitempty"`
	MemoryPagesLimit int64                  `protobuf:"varint,5,opt,name=memory_pages_limit,json=memoryPagesLimit,proto3" json:"memory_pages_limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetCompression() CheckpointCompression {
	if x != nil {
		return x.Compression
	}
	return CheckpointCompression_CHECKPOINT_COMPRESSION_UNSPECIFIED
}

func (x *CreateRequest) GetIncremental() bool {
	if x != nil {
		return x.Incremental
	}
	return false
}

func (x *CreateRequest) GetMemoryPagesLimit() int64 {
	if x != nil {
		return x.MemoryPagesLimit
	}
	return 0
}

type CreateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId    string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MemorySizeBytes int64                  `protobuf:"varint,3,opt,name=memory_size_bytes,json=memorySizeBytes,proto3" json:"memory_size_bytes,omitempty"`
	DiskSizeBytes   int64                  `protobuf:"varint,4,opt,name=disk_size_bytes,json=diskSizeBytes,proto3" json:"disk_size_bytes,omitempty"`
	DurationMs      int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *CreateResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateResponse) GetMemorySizeBytes() int64 {
	if x != nil {
		return x.MemorySizeBytes
	}
	return 0
}

func (x *CreateResponse) GetDiskSizeBytes() int64 {
	if x != nil {
		return x.DiskSizeBytes
	}
	return 0
}

func (x *CreateResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	IncludeExpired bool                   `protobuf:"varint,2,opt,name=include_expired,json=includeExpired,proto3" json:"include_expired,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ListRequest) GetIncludeExpired() bool {
	if x != nil {
		return x.IncludeExpired
	}
	return false
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkpoints   []*CheckpointDetail    `protobuf:"bytes,1,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetCheckpoints() []*CheckpointDetail {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{6}
}

type RestoreRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId    string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	TargetSandboxId string                 `protobuf:"bytes,2,opt,name=target_sandbox_id,json=targetSandboxId,proto3" json:"target_sandbox_id,omitempty"`
	Suspended       bool                   `protobuf:"varint,3,opt,name=suspended,proto3" json:"suspended,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{7}
}

func (x *RestoreRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *RestoreRequest) GetTargetSandboxId() string {
	if x != nil {
		return x.TargetSandboxId
	}
	return ""
}

func (x *RestoreRequest) GetSuspended() bool {
	if x != nil {
		return x.Suspended
	}
	return false
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	VsockCid      uint32                 `protobuf:"varint,2,opt,name=vsock_cid,json=vsockCid,proto3" json:"vsock_cid,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{8}
}

func (x *RestoreResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RestoreResponse) GetVsockCid() uint32 {
	if x != nil {
		return x.VsockCid
	}
	return 0
}

func (x *RestoreResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatusRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type GetStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Checkpoint      *CheckpointDetail      `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Stage           CheckpointStage        `protobuf:"varint,2,opt,name=stage,proto3,enum=coco.v1.CheckpointStage" json:"stage,omitempty"`
	ProgressPercent int32                  `protobuf:"varint,3,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	BytesWritten    int64                  `protobuf:"varint,4,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	TotalBytes      int64                  `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_checkpoint_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_checkpoint_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatusResponse) GetCheckpoint() *CheckpointDetail {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *GetStatusResponse) GetStage() CheckpointStage {
	if x != nil {
		return x.Stage
	}
	return CheckpointStage_CHECKPOINT_STAGE_UNSPECIFIED
}

func (x *GetStatusResponse) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *GetStatusResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *GetStatusResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

var File_proto_coco_v1_checkpoint_proto protoreflect.FileDescriptor

const file_proto_coco_v1_checkpoint_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/coco/v1/checkpoint.proto\x12\acoco.v1\"\xba\x04\n" +
	"\x10CheckpointDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12#\n" +
	"\ris_compressed\x18\x06 \x01(\bR\fisCompressed\x12@\n" +
	"\vcompression\x18\a \x01(\x0e2\x1e.coco.v1.CheckpointCompressionR\vcompression\x12*\n" +
	"\x11memory_size_bytes\x18\b \x01(\x03R\x0fmemorySizeBytes\x12&\n" +
	"\x0fdisk_size_bytes\x18\t \x01(\x03R\rdiskSizeBytes\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\x03R\n" +
	"durationMs\x12 \n" +
	"\vincremental\x18\v \x01(\bR\vincremental\x120\n" +
	"\x14parent_checkpoint_id\x18\f \x01(\tR\x12parentCheckpointId\x12C\n" +
	"\bmetadata\x18\r \x03(\v2'.coco.v1.CheckpointDetail.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x01\n" +
	"\rCreateRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12@\n" +
	"\vcompression\x18\x03 \x01(\x0e2\x1e.coco.v1.CheckpointCompressionR\vcompression\x12 \n" +
	"\vincremental\x18\x04 \x01(\bR\vincremental\x12,\n" +
	"\x12memory_pages_limit\x18\x05 \x01(\x03R\x10memoryPagesLimit\"\xc9\x01\n" +
	"\x0eCreateResponse\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12*\n" +
	"\x11memory_size_bytes\x18\x03 \x01(\x03R\x0fmemorySizeBytes\x12&\n" +
	"\x0fdisk_size_bytes\x18\x04 \x01(\x03R\rdiskSizeBytes\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"U\n" +
	"\vListRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12'\n" +
	"\x0finclude_expired\x18\x02 \x01(\bR\x0eincludeExpired\"K\n" +
	"\fListResponse\x12;\n" +
	"\vcheckpoints\x18\x01 \x03(\v2\x19.coco.v1.CheckpointDetailR\vcheckpoints\"4\n" +
	"\rDeleteRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\"\x10\n" +
	"\x0eDeleteResponse\"\x7f\n" +
	"\x0eRestoreRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12*\n" +
	"\x11target_sandbox_id\x18\x02 \x01(\tR\x0ftargetSandboxId\x12\x1c\n" +
	"\tsuspended\x18\x03 \x01(\bR\tsuspended\"n\n" +
	"\x0fRestoreResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1b\n" +
	"\tvsock_cid\x18\x02 \x01(\rR\bvsockCid\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"7\n" +
	"\x10GetStatusRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\"\xef\x01\n" +
	"\x11GetStatusResponse\x129\n" +
	"\n" +
	"checkpoint\x18\x01 \x01(\v2\x19.coco.v1.CheckpointDetailR\n" +
	"checkpoint\x12.\n" +
	"\x05stage\x18\x02 \x01(\x0e2\x18.coco.v1.CheckpointStageR\x05stage\x12)\n" +
	"\x10progress_percent\x18\x03 \x01(\x05R\x0fprogressPercent\x12#\n" +
	"\rbytes_written\x18\x04 \x01(\x03R\fbytesWritten\x12\x1f\n" +
	"\vtotal_bytes\x18\x05 \x01(\x03R\n" +
	"totalBytes*\xa1\x01\n" +
	"\x15CheckpointCompression\x12&\n" +
	"\"CHECKPOINT_COMPRESSION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCHECKPOINT_COMPRESSION_NONE\x10\x01\x12\x1f\n" +
	"\x1bCHECKPOINT_COMPRESSION_ZSTD\x10\x02\x12\x1e\n" +
	"\x1aCHECKPOINT_COMPRESSION_LZ4\x10\x03*\x8c\x01\n" +
	"\x0fCheckpointStage\x12 \n" +
	"\x1cCHECKPOINT_STAGE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CHECKPOINT_STAGE_MEMORY\x10\x01\x12\x19\n" +
	"\x15CHECKPOINT_STAGE_DISK\x10\x02\x12\x1f\n" +
	"\x1bCHECKPOINT_STAGE_FINALIZING\x10\x032\xc0\x02\n" +
	"\x11CheckpointService\x129\n" +
	"\x06Create\x12\x16.coco.v1.CreateRequest\x1a\x17.coco.v1.CreateResponse\x123\n" +
	"\x04List\x12\x14.coco.v1.ListRequest\x1a\x15.coco.v1.ListResponse\x129\n" +
	"\x06Delete\x12\x16.coco.v1.DeleteRequest\x1a\x17.coco.v1.DeleteResponse\x12<\n" +
	"\aRestore\x12\x17.coco.v1.RestoreRequest\x1a\x18.coco.v1.RestoreResponse\x12B\n" +
	"\tGetStatus\x12\x19.coco.v1.GetStatusRequest\x1a\x1a.coco.v1.GetStatusResponseB)Z'github.com/coco-sandbox/coco/pkg/api/v1b\x06proto3"

var (
	file_proto_coco_v1_checkpoint_proto_rawDescOnce sync.Once
	file_proto_coco_v1_checkpoint_proto_rawDescData []byte
)

func file_proto_coco_v1_checkpoint_proto_rawDescGZIP() []byte {
	file_proto_coco_v1_checkpoint_proto_rawDescOnce.Do(func() {
		file_proto_coco_v1_checkpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coco_v1_checkpoint_proto_rawDesc), len(file_proto_coco_v1_checkpoint_proto_rawDesc)))
	})
	return file_proto_coco_v1_checkpoint_proto_rawDescData
}

var file_proto_coco_v1_checkpoint_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_coco_v1_checkpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_coco_v1_checkpoint_proto_goTypes = []any{
	(CheckpointCompression)(0), // 0: coco.v1.CheckpointCompression
	(CheckpointStage)(0),       // 1: coco.v1.CheckpointStage
	(*CheckpointDetail)(nil),   // 2: coco.v1.CheckpointDetail
	(*CreateRequest)(nil),      // 3: coco.v1.CreateRequest
	(*CreateResponse)(nil),     // 4: coco.v1.CreateResponse
	(*ListRequest)(nil),        // 5: coco.v1.ListRequest
	(*ListResponse)(nil),       // 6: coco.v1.ListResponse
	(*DeleteRequest)(nil),      // 7: coco.v1.DeleteRequest
	(*DeleteResponse)(nil),     // 8: coco.v1.DeleteResponse
	(*RestoreRequest)(nil),     // 9: coco.v1.RestoreRequest
	(*RestoreResponse)(nil),    // 10: coco.v1.RestoreResponse
	(*GetStatusRequest)(nil),   // 11: coco.v1.GetStatusRequest
	(*GetStatusResponse)(nil),  // 12: coco.v1.GetStatusResponse
	nil,                        // 13: coco.v1.CheckpointDetail.MetadataEntry
}
var file_proto_coco_v1_checkpoint_proto_depIdxs = []int32{
	0,  // 0: coco.v1.CheckpointDetail.compression:type_name -> coco.v1.CheckpointCompression
	13, // 1: coco.v1.CheckpointDetail.metadata:type_name -> coco.v1.CheckpointDetail.MetadataEntry
	0,  // 2: coco.v1.CreateRequest.compression:type_name -> coco.v1.CheckpointCompression
	2,  // 3: coco.v1.ListResponse.checkpoints:type_name -> coco.v1.CheckpointDetail
	2,  // 4: coco.v1.GetStatusResponse.checkpoint:type_name -> coco.v1.CheckpointDetail
	1,  // 5: coco.v1.GetStatusResponse.stage:type_name -> coco.v1.CheckpointStage
	3,  // 6: coco.v1.CheckpointService.Create:input_type -> coco.v1.CreateRequest
	5,  // 7: coco.v1.CheckpointService.List:input_type -> coco.v1.ListRequest
	7,  // 8: coco.v1.CheckpointService.Delete:input_type -> coco.v1.DeleteRequest
	9,  // 9: coco.v1.CheckpointService.Restore:input_type -> coco.v1.RestoreRequest
	11, // 10: coco.v1.CheckpointService.GetStatus:input_type -> coco.v1.GetStatusRequest
	4,  // 11: coco.v1.CheckpointService.Create:output_type -> coco.v1.CreateResponse
	6,  // 12: coco.v1.CheckpointService.List:output_type -> coco.v1.ListResponse
	8,  // 13: coco.v1.CheckpointService.Delete:output_type -> coco.v1.DeleteResponse
	10, // 14: coco.v1.CheckpointService.Restore:output_type -> coco.v1.RestoreResponse
	12, // 15: coco.v1.CheckpointService.GetStatus:output_type -> coco.v1.GetStatusResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_coco_v1_checkpoint_proto_init() }
func file_proto_coco_v1_checkpoint_proto_init() {
	if File_proto_coco_v1_checkpoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coco_v1_checkpoint_proto_rawDesc), len(file_proto_coco_v1_checkpoint_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coco_v1_checkpoint_proto_goTypes,
		DependencyIndexes: file_proto_coco_v1_checkpoint_proto_depIdxs,
		EnumInfos:         file_proto_coco_v1_checkpoint_proto_enumTypes,
		MessageInfos:      file_proto_coco_v1_checkpoint_proto_msgTypes,
	}.Build()
	File_proto_coco_v1_checkpoint_proto = out.File
	file_proto_coco_v1_checkpoint_proto_goTypes = nil
	file_proto_coco_v1_checkpoint_proto_depIdxs = nil
}
