// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/coco/v1/network.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SandboxId     string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	IngressRules  []string               `protobuf:"bytes,3,rep,name=ingress_rules,json=ingressRules,proto3" json:"ingress_rules,omitempty"`
	EgressRules   []string               `protobuf:"bytes,4,rep,name=egress_rules,json=egressRules,proto3" json:"egress_rules,omitempty"`
	DefaultAllow  bool                   `protobuf:"varint,5,opt,name=default_allow,json=defaultAllow,proto3" json:"default_allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicy) Reset() {
	*x = NetworkPolicy{}
	mi := &file_proto_coco_v1_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicy) ProtoMessage() {}

func (x *NetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicy.ProtoReflect.Descriptor instead.
func (*NetworkPolicy) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_network_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkPolicy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NetworkPolicy) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *NetworkPolicy) GetIngressRules() []string {
	if x != nil {
		return x.IngressRules
	}
	return nil
}

func (x *NetworkPolicy) GetEgressRules() []string {
	if x != nil {
		return x.EgressRules
	}
	return nil
}

func (x *NetworkPolicy) GetDefaultAllow() bool {
	if x != nil {
		return x.DefaultAllow
	}
	return false
}

type AllocateIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateIPRequest) Reset() {
	*x = AllocateIPRequest{}
	mi := &file_proto_coco_v1_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateIPRequest) ProtoMessage() {}

func (x *AllocateIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateIPRequest.ProtoReflect.Descriptor instead.
func (*AllocateIPRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_network_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateIPRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type AllocateIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Gateway       string                 `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateIPResponse) Reset() {
	*x = AllocateIPResponse{}
	mi := &file_proto_coco_v1_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateIPResponse) ProtoMessage() {}

func (x *AllocateIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateIPResponse.ProtoReflect.Descriptor instead.
func (*AllocateIPResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_network_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateIPResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AllocateIPResponse) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

type ReleaseIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIPRequest) Reset() {
	*x = ReleaseIPRequest{}
	mi := &file_proto_coco_v1_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIPRequest) ProtoMessage() {}

func (x *ReleaseIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIPRequest.ProtoReflect.Descriptor instead.
func (*ReleaseIPRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_network_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseIPRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type NetworkStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	RxBytes       int64                  `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       int64                  `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxPackets     int64                  `protobuf:"varint,4,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`
	TxPackets     int64                  `protobuf:"varint,5,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_proto_coco_v1_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_network_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkStats) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *NetworkStats) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkStats) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *NetworkStats) GetRxPackets() int64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *NetworkStats) GetTxPackets() int64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

var File_proto_coco_v1_network_proto protoreflect.FileDescriptor

const file_proto_coco_v1_network_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/coco/v1/network.proto\x12\acoco.v1\"\xab\x01\n" +
	"\rNetworkPolicy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12#\n" +
	"\ringress_rules\x18\x03 \x03(\tR\fingressRules\x12!\n" +
	"\fegress_rules\x18\x04 \x03(\tR\vegressRules\x12#\n" +
	"\rdefault_allow\x18\x05 \x01(\bR\fdefaultAllow\"2\n" +
	"\x11AllocateIPRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\">\n" +
	"\x12AllocateIPResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\"1\n" +
	"\x10ReleaseIPRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\xa1\x01\n" +
	"\fNetworkStats\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x03R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x03R\atxBytes\x12\x1d\n" +
	"\n" +
	"rx_packets\x18\x04 \x01(\x03R\trxPackets\x12\x1d\n" +
	"\n" +
	"tx_packets\x18\x05 \x01(\x03R\ttxPacketsB)Z'github.com/coco-sandbox/coco/pkg/api/v1b\x06proto3"

var (
	file_proto_coco_v1_network_proto_rawDescOnce sync.Once
	file_proto_coco_v1_network_proto_rawDescData []byte
)

func file_proto_coco_v1_network_proto_rawDescGZIP() []byte {
	file_proto_coco_v1_network_proto_rawDescOnce.Do(func() {
		file_proto_coco_v1_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coco_v1_network_proto_rawDesc), len(file_proto_coco_v1_network_proto_rawDesc)))
	})
	return file_proto_coco_v1_network_proto_rawDescData
}

var file_proto_coco_v1_network_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_coco_v1_network_proto_goTypes = []any{
	(*NetworkPolicy)(nil),      // 0: coco.v1.NetworkPolicy
	(*AllocateIPRequest)(nil),  // 1: coco.v1.AllocateIPRequest
	(*AllocateIPResponse)(nil), // 2: coco.v1.AllocateIPResponse
	(*ReleaseIPRequest)(nil),   // 3: coco.v1.ReleaseIPRequest
	(*NetworkStats)(nil),       // 4: coco.v1.NetworkStats
}
var file_proto_coco_v1_network_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_coco_v1_network_proto_init() }
func file_proto_coco_v1_network_proto_init() {
	if File_proto_coco_v1_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coco_v1_network_proto_rawDesc), len(file_proto_coco_v1_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_coco_v1_network_proto_goTypes,
		DependencyIndexes: file_proto_coco_v1_network_proto_depIdxs,
		MessageInfos:      file_proto_coco_v1_network_proto_msgTypes,
	}.Build()
	File_proto_coco_v1_network_proto = out.File
	file_proto_coco_v1_network_proto_goTypes = nil
	file_proto_coco_v1_network_proto_depIdxs = nil
}
