// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/coco/v1/node.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Kernel        string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Initrd        string                 `protobuf:"bytes,4,opt,name=initrd,proto3" json:"initrd,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Vcpus         int32                  `protobuf:"varint,6,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	VsockCid      uint32                 `protobuf:"varint,7,opt,name=vsock_cid,json=vsockCid,proto3" json:"vsock_cid,omitempty"`
	NetworkMode   string                 `protobuf:"bytes,8,opt,name=network_mode,json=networkMode,proto3" json:"network_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootSandboxRequest) Reset() {
	*x = BootSandboxRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootSandboxRequest) ProtoMessage() {}

func (x *BootSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootSandboxRequest.ProtoReflect.Descriptor instead.
func (*BootSandboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *BootSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *BootSandboxRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *BootSandboxRequest) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *BootSandboxRequest) GetInitrd() string {
	if x != nil {
		return x.Initrd
	}
	return ""
}

func (x *BootSandboxRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *BootSandboxRequest) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *BootSandboxRequest) GetVsockCid() uint32 {
	if x != nil {
		return x.VsockCid
	}
	return 0
}

func (x *BootSandboxRequest) GetNetworkMode() string {
	if x != nil {
		return x.NetworkMode
	}
	return ""
}

type BootSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	VsockCid      uint32                 `protobuf:"varint,3,opt,name=vsock_cid,json=vsockCid,proto3" json:"vsock_cid,omitempty"`
	TapDevice     string                 `protobuf:"bytes,4,opt,name=tap_device,json=tapDevice,proto3" json:"tap_device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootSandboxResponse) Reset() {
	*x = BootSandboxResponse{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootSandboxResponse) ProtoMessage() {}

func (x *BootSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootSandboxResponse.ProtoReflect.Descriptor instead.
func (*BootSandboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *BootSandboxResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *BootSandboxResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *BootSandboxResponse) GetVsockCid() uint32 {
	if x != nil {
		return x.VsockCid
	}
	return 0
}

func (x *BootSandboxResponse) GetTapDevice() string {
	if x != nil {
		return x.TapDevice
	}
	return ""
}

type DestroyVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVMRequest) Reset() {
	*x = DestroyVMRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVMRequest) ProtoMessage() {}

func (x *DestroyVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVMRequest.ProtoReflect.Descriptor instead.
func (*DestroyVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyVMRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type DestroyVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVMResponse) Reset() {
	*x = DestroyVMResponse{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVMResponse) ProtoMessage() {}

func (x *DestroyVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVMResponse.ProtoReflect.Descriptor instead.
func (*DestroyVMResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{3}
}

type PauseVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseVMRequest) Reset() {
	*x = PauseVMRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseVMRequest) ProtoMessage() {}

func (x *PauseVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseVMRequest.ProtoReflect.Descriptor instead.
func (*PauseVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *PauseVMRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type PauseVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseVMResponse) Reset() {
	*x = PauseVMResponse{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseVMResponse) ProtoMessage() {}

func (x *PauseVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseVMResponse.ProtoReflect.Descriptor instead.
func (*PauseVMResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{5}
}

type ResumeVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeVMRequest) Reset() {
	*x = ResumeVMRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeVMRequest) ProtoMessage() {}

func (x *ResumeVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeVMRequest.ProtoReflect.Descriptor instead.
func (*ResumeVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *ResumeVMRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type ResumeVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeVMResponse) Reset() {
	*x = ResumeVMResponse{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeVMResponse) ProtoMessage() {}

func (x *ResumeVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeVMResponse.ProtoReflect.Descriptor instead.
func (*ResumeVMResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{7}
}

type ForkVMRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentSandboxId string                 `protobuf:"bytes,1,opt,name=parent_sandbox_id,json=parentSandboxId,proto3" json:"parent_sandbox_id,omitempty"`
	NewSandboxId    string                 `protobuf:"bytes,2,opt,name=new_sandbox_id,json=newSandboxId,proto3" json:"new_sandbox_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ForkVMRequest) Reset() {
	*x = ForkVMRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkVMRequest) ProtoMessage() {}

func (x *ForkVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkVMRequest.ProtoReflect.Descriptor instead.
func (*ForkVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *ForkVMRequest) GetParentSandboxId() string {
	if x != nil {
		return x.ParentSandboxId
	}
	return ""
}

func (x *ForkVMRequest) GetNewSandboxId() string {
	if x != nil {
		return x.NewSandboxId
	}
	return ""
}

type ForkVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	VsockCid      uint32                 `protobuf:"varint,2,opt,name=vsock_cid,json=vsockCid,proto3" json:"vsock_cid,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkVMResponse) Reset() {
	*x = ForkVMResponse{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkVMResponse) ProtoMessage() {}

func (x *ForkVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkVMResponse.ProtoReflect.Descriptor instead.
func (*ForkVMResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *ForkVMResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ForkVMResponse) GetVsockCid() uint32 {
	if x != nil {
		return x.VsockCid
	}
	return 0
}

func (x *ForkVMResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ExecVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,5,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecVMRequest) Reset() {
	*x = ExecVMRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecVMRequest) ProtoMessage() {}

func (x *ExecVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecVMRequest.ProtoReflect.Descriptor instead.
func (*ExecVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *ExecVMRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecVMRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *ExecVMRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecVMRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecVMRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecVMRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ExecVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecVMResponse) Reset() {
	*x = ExecVMResponse{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecVMResponse) ProtoMessage() {}

func (x *ExecVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecVMResponse.ProtoReflect.Descriptor instead.
func (*ExecVMResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{11}
}

func (x *ExecVMResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecVMResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecVMResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecVMResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type StreamingExecVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,5,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Interactive   bool                   `protobuf:"varint,7,opt,name=interactive,proto3" json:"interactive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingExecVMRequest) Reset() {
	*x = StreamingExecVMRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingExecVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingExecVMRequest) ProtoMessage() {}

func (x *StreamingExecVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingExecVMRequest.ProtoReflect.Descriptor instead.
func (*StreamingExecVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *StreamingExecVMRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StreamingExecVMRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *StreamingExecVMRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *StreamingExecVMRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StreamingExecVMRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *StreamingExecVMRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *StreamingExecVMRequest) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

type GetNodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatusRequest) Reset() {
	*x = GetNodeStatusRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatusRequest) ProtoMessage() {}

func (x *GetNodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{13}
}

type NodeStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ActiveSandboxes int32                  `protobuf:"varint,2,opt,name=active_sandboxes,json=activeSandboxes,proto3" json:"active_sandboxes,omitempty"`
	PoolSize        int32                  `protobuf:"varint,3,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	PoolFree        int32                  `protobuf:"varint,4,opt,name=pool_free,json=poolFree,proto3" json:"pool_free,omitempty"`
	MemoryTotalMb   uint64                 `protobuf:"varint,5,opt,name=memory_total_mb,json=memoryTotalMb,proto3" json:"memory_total_mb,omitempty"`
	MemoryUsedMb    uint64                 `protobuf:"varint,6,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	CpuPercent      int32                  `protobuf:"varint,7,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	Healthy         bool                   `protobuf:"varint,8,opt,name=healthy,proto3" json:"healthy,omitempty"`
	LastUpdate      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Capabilities    map[string]string      `protobuf:"bytes,10,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{14}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetActiveSandboxes() int32 {
	if x != nil {
		return x.ActiveSandboxes
	}
	return 0
}

func (x *NodeStatus) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *NodeStatus) GetPoolFree() int32 {
	if x != nil {
		return x.PoolFree
	}
	return 0
}

func (x *NodeStatus) GetMemoryTotalMb() uint64 {
	if x != nil {
		return x.MemoryTotalMb
	}
	return 0
}

func (x *NodeStatus) GetMemoryUsedMb() uint64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *NodeStatus) GetCpuPercent() int32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *NodeStatus) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

func (x *NodeStatus) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	MemoryMb      uint64                 `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Cpus          int32                  `protobuf:"varint,4,opt,name=cpus,proto3" json:"cpus,omitempty"`
	PoolSize      int32                  `protobuf:"varint,5,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	Capabilities  map[string]string      `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RegisterNodeRequest) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *RegisterNodeRequest) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *RegisterNodeRequest) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *RegisterNodeRequest) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterNodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedNodeId string                 `protobuf:"bytes,3,opt,name=assigned_node_id,json=assignedNodeId,proto3" json:"assigned_node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNodeResponse) GetAssignedNodeId() string {
	if x != nil {
		return x.AssignedNodeId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        *NodeStatus            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{18}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type ReportMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMetricsRequest) Reset() {
	*x = ReportMetricsRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMetricsRequest) ProtoMessage() {}

func (x *ReportMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMetricsRequest.ProtoReflect.Descriptor instead.
func (*ReportMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{19}
}

func (x *ReportMetricsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{20}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ReportMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMetricsResponse) Reset() {
	*x = ReportMetricsResponse{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMetricsResponse) ProtoMessage() {}

func (x *ReportMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMetricsResponse.ProtoReflect.Descriptor instead.
func (*ReportMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{21}
}

type GetPoolStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolStatusRequest) Reset() {
	*x = GetPoolStatusRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolStatusRequest) ProtoMessage() {}

func (x *GetPoolStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPoolStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{22}
}

type PoolStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSlots    int32                  `protobuf:"varint,1,opt,name=total_slots,json=totalSlots,proto3" json:"total_slots,omitempty"`
	FreeSlots     int32                  `protobuf:"varint,2,opt,name=free_slots,json=freeSlots,proto3" json:"free_slots,omitempty"`
	WarmVms       int32                  `protobuf:"varint,3,opt,name=warm_vms,json=warmVms,proto3" json:"warm_vms,omitempty"`
	ColdVms       int32                  `protobuf:"varint,4,opt,name=cold_vms,json=coldVms,proto3" json:"cold_vms,omitempty"`
	ActiveVms     int32                  `protobuf:"varint,5,opt,name=active_vms,json=activeVms,proto3" json:"active_vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolStatus) Reset() {
	*x = PoolStatus{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStatus) ProtoMessage() {}

func (x *PoolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStatus.ProtoReflect.Descriptor instead.
func (*PoolStatus) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{23}
}

func (x *PoolStatus) GetTotalSlots() int32 {
	if x != nil {
		return x.TotalSlots
	}
	return 0
}

func (x *PoolStatus) GetFreeSlots() int32 {
	if x != nil {
		return x.FreeSlots
	}
	return 0
}

func (x *PoolStatus) GetWarmVms() int32 {
	if x != nil {
		return x.WarmVms
	}
	return 0
}

func (x *PoolStatus) GetColdVms() int32 {
	if x != nil {
		return x.ColdVms
	}
	return 0
}

func (x *PoolStatus) GetActiveVms() int32 {
	if x != nil {
		return x.ActiveVms
	}
	return 0
}

type PrewarmPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrewarmPoolRequest) Reset() {
	*x = PrewarmPoolRequest{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrewarmPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrewarmPoolRequest) ProtoMessage() {}

func (x *PrewarmPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrewarmPoolRequest.ProtoReflect.Descriptor instead.
func (*PrewarmPoolRequest) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{24}
}

func (x *PrewarmPoolRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PrewarmPoolRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type PrewarmPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warmed        int32                  `protobuf:"varint,1,opt,name=warmed,proto3" json:"warmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrewarmPoolResponse) Reset() {
	*x = PrewarmPoolResponse{}
	mi := &file_proto_coco_v1_node_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrewarmPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrewarmPoolResponse) ProtoMessage() {}

func (x *PrewarmPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coco_v1_node_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrewarmPoolResponse.ProtoReflect.Descriptor instead.
func (*PrewarmPoolResponse) Descriptor() ([]byte, []int) {
	return file_proto_coco_v1_node_proto_rawDescGZIP(), []int{25}
}

func (x *PrewarmPoolResponse) GetWarmed() int32 {
	if x != nil {
		return x.Warmed
	}
	return 0
}

var File_proto_coco_v1_node_proto protoreflect.FileDescriptor

const file_proto_coco_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x18proto/coco/v1/node.proto\x12\acoco.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18proto/coco/v1/coco.proto\"\xf7\x01\n" +
	"\x12BootSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\x12\x16\n" +
	"\x06initrd\x18\x04 \x01(\tR\x06initrd\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x05R\bmemoryMb\x12\x14\n" +
	"\x05vcpus\x18\x06 \x01(\x05R\x05vcpus\x12\x1b\n" +
	"\tvsock_cid\x18\a \x01(\rR\bvsockCid\x12!\n" +
	"\fnetwork_mode\x18\b \x01(\tR\vnetworkMode\"\x82\x01\n" +
	"\x13BootSandboxResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x1b\n" +
	"\tvsock_cid\x18\x03 \x01(\rR\bvsockCid\x12\x1d\n" +
	"\n" +
	"tap_device\x18\x04 \x01(\tR\ttapDevice\"1\n" +
	"\x10DestroyVMRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\x13\n" +
	"\x11DestroyVMResponse\"/\n" +
	"\x0ePauseVMRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\x11\n" +
	"\x0fPauseVMResponse\"0\n" +
	"\x0fResumeVMRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\x12\n" +
	"\x10ResumeVMResponse\"a\n" +
	"\rForkVMRequest\x12*\n" +
	"\x11parent_sandbox_id\x18\x01 \x01(\tR\x0fparentSandboxId\x12$\n" +
	"\x0enew_sandbox_id\x18\x02 \x01(\tR\fnewSandboxId\"m\n" +
	"\x0eForkVMResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1b\n" +
	"\tvsock_cid\x18\x02 \x01(\rR\bvsockCid\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"\xa6\x01\n" +
	"\rExecVMRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x05 \x01(\tR\n" +
	"workingDir\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMs\"~\n" +
	"\x0eExecVMResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\xd1\x01\n" +
	"\x16StreamingExecVMRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x05 \x01(\tR\n" +
	"workingDir\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMs\x12 \n" +
	"\vinteractive\x18\a \x01(\bR\vinteractive\"\x16\n" +
	"\x14GetNodeStatusRequest\"\xdc\x03\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12)\n" +
	"\x10active_sandboxes\x18\x02 \x01(\x05R\x0factiveSandboxes\x12\x1b\n" +
	"\tpool_size\x18\x03 \x01(\x05R\bpoolSize\x12\x1b\n" +
	"\tpool_free\x18\x04 \x01(\x05R\bpoolFree\x12&\n" +
	"\x0fmemory_total_mb\x18\x05 \x01(\x04R\rmemoryTotalMb\x12$\n" +
	"\x0ememory_used_mb\x18\x06 \x01(\x04R\fmemoryUsedMb\x12\x1f\n" +
	"\vcpu_percent\x18\a \x01(\x05R\n" +
	"cpuPercent\x12\x18\n" +
	"\ahealthy\x18\b \x01(\bR\ahealthy\x12;\n" +
	"\vlast_update\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\x12I\n" +
	"\fcapabilities\x18\n" +
	" \x03(\v2%.coco.v1.NodeStatus.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x02\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x04R\bmemoryMb\x12\x12\n" +
	"\x04cpus\x18\x04 \x01(\x05R\x04cpus\x12\x1b\n" +
	"\tpool_size\x18\x05 \x01(\x05R\bpoolSize\x12R\n" +
	"\fcapabilities\x18\x06 \x03(\v2..coco.v1.RegisterNodeRequest.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x10assigned_node_id\x18\x03 \x01(\tR\x0eassignedNodeId\"X\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12+\n" +
	"\x06status\x18\x02 \x01(\v2\x13.coco.v1.NodeStatusR\x06status\"t\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"Z\n" +
	"\x14ReportMetricsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12)\n" +
	"\ametrics\x18\x02 \x03(\v2\x0f.coco.v1.MetricR\ametrics\"l\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x17\n" +
	"\x15ReportMetricsResponse\"\x16\n" +
	"\x14GetPoolStatusRequest\"\xa1\x01\n" +
	"\n" +
	"PoolStatus\x12\x1f\n" +
	"\vtotal_slots\x18\x01 \x01(\x05R\n" +
	"totalSlots\x12\x1d\n" +
	"\n" +
	"free_slots\x18\x02 \x01(\x05R\tfreeSlots\x12\x19\n" +
	"\bwarm_vms\x18\x03 \x01(\x05R\awarmVms\x12\x19\n" +
	"\bcold_vms\x18\x04 \x01(\x05R\acoldVms\x12\x1d\n" +
	"\n" +
	"active_vms\x18\x05 \x01(\x05R\tactiveVms\"K\n" +
	"\x12PrewarmPoolRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\"-\n" +
	"\x13PrewarmPoolResponse\x12\x16\n" +
	"\x06warmed\x18\x01 \x01(\x05R\x06warmed2\x8f\a\n" +
	"\vNodeService\x12H\n" +
	"\vBootSandbox\x12\x1b.coco.v1.BootSandboxRequest\x1a\x1c.coco.v1.BootSandboxResponse\x12B\n" +
	"\tDestroyVM\x12\x19.coco.v1.DestroyVMRequest\x1a\x1a.coco.v1.DestroyVMResponse\x12<\n" +
	"\aPauseVM\x12\x17.coco.v1.PauseVMRequest\x1a\x18.coco.v1.PauseVMResponse\x12?\n" +
	"\bResumeVM\x12\x18.coco.v1.ResumeVMRequest\x1a\x19.coco.v1.ResumeVMResponse\x129\n" +
	"\x06ForkVM\x12\x16.coco.v1.ForkVMRequest\x1a\x17.coco.v1.ForkVMResponse\x129\n" +
	"\x06ExecVM\x12\x16.coco.v1.ExecVMRequest\x1a\x17.coco.v1.ExecVMResponse\x12H\n" +
	"\x0fStreamingExecVM\x12\x1f.coco.v1.StreamingExecVMRequest\x1a\x12.coco.v1.ExecChunk0\x01\x12C\n" +
	"\rGetNodeStatus\x12\x1d.coco.v1.GetNodeStatusRequest\x1a\x13.coco.v1.NodeStatus\x12K\n" +
	"\fRegisterNode\x12\x1c.coco.v1.RegisterNodeRequest\x1a\x1d.coco.v1.RegisterNodeResponse\x12B\n" +
	"\tHeartbeat\x12\x19.coco.v1.HeartbeatRequest\x1a\x1a.coco.v1.HeartbeatResponse\x12N\n" +
	"\rReportMetrics\x12\x1d.coco.v1.ReportMetricsRequest\x1a\x1e.coco.v1.ReportMetricsResponse\x12C\n" +
	"\rGetPoolStatus\x12\x1d.coco.v1.GetPoolStatusRequest\x1a\x13.coco.v1.PoolStatus\x12H\n" +
	"\vPrewarmPool\x12\x1b.coco.v1.PrewarmPoolRequest\x1a\x1c.coco.v1.PrewarmPoolResponseB)Z'github.com/coco-sandbox/coco/pkg/api/v1b\x06proto3"

var (
	file_proto_coco_v1_node_proto_rawDescOnce sync.Once
	file_proto_coco_v1_node_proto_rawDescData []byte
)

func file_proto_coco_v1_node_proto_rawDescGZIP() []byte {
	file_proto_coco_v1_node_proto_rawDescOnce.Do(func() {
		file_proto_coco_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coco_v1_node_proto_rawDesc), len(file_proto_coco_v1_node_proto_rawDesc)))
	})
	return file_proto_coco_v1_node_proto_rawDescData
}

var file_proto_coco_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_coco_v1_node_proto_goTypes = []any{
	(*BootSandboxRequest)(nil),     // 0: coco.v1.BootSandboxRequest
	(*BootSandboxResponse)(nil),    // 1: coco.v1.BootSandboxResponse
	(*DestroyVMRequest)(nil),       // 2: coco.v1.DestroyVMRequest
	(*DestroyVMResponse)(nil),      // 3: coco.v1.DestroyVMResponse
	(*PauseVMRequest)(nil),         // 4: coco.v1.PauseVMRequest
	(*PauseVMResponse)(nil),        // 5: coco.v1.PauseVMResponse
	(*ResumeVMRequest)(nil),        // 6: coco.v1.ResumeVMRequest
	(*ResumeVMResponse)(nil),       // 7: coco.v1.ResumeVMResponse
	(*ForkVMRequest)(nil),          // 8: coco.v1.ForkVMRequest
	(*ForkVMResponse)(nil),         // 9: coco.v1.ForkVMResponse
	(*ExecVMRequest)(nil),          // 10: coco.v1.ExecVMRequest
	(*ExecVMResponse)(nil),         // 11: coco.v1.ExecVMResponse
	(*StreamingExecVMRequest)(nil), // 12: coco.v1.StreamingExecVMRequest
	(*GetNodeStatusRequest)(nil),   // 13: coco.v1.GetNodeStatusRequest
	(*NodeStatus)(nil),             // 14: coco.v1.NodeStatus
	(*RegisterNodeRequest)(nil),    // 15: coco.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),   // 16: coco.v1.RegisterNodeResponse
	(*HeartbeatRequest)(nil),       // 17: coco.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 18: coco.v1.HeartbeatResponse
	(*ReportMetricsRequest)(nil),   // 19: coco.v1.ReportMetricsRequest
	(*Metric)(nil),                 // 20: coco.v1.Metric
	(*ReportMetricsResponse)(nil),  // 21: coco.v1.ReportMetricsResponse
	(*GetPoolStatusRequest)(nil),   // 22: coco.v1.GetPoolStatusRequest
	(*PoolStatus)(nil),             // 23: coco.v1.PoolStatus
	(*PrewarmPoolRequest)(nil),     // 24: coco.v1.PrewarmPoolRequest
	(*PrewarmPoolResponse)(nil),    // 25: coco.v1.PrewarmPoolResponse
	nil,                            // 26: coco.v1.NodeStatus.CapabilitiesEntry
	nil,                            // 27: coco.v1.RegisterNodeRequest.CapabilitiesEntry
	(*timestamppb.Timestamp)(nil),  // 28: google.protobuf.Timestamp
	(*ExecChunk)(nil),              // 29: coco.v1.ExecChunk
}
var file_proto_coco_v1_node_proto_depIdxs = []int32{
	28, // 0: coco.v1.NodeStatus.last_update:type_name -> google.protobuf.Timestamp
	26, // 1: coco.v1.NodeStatus.capabilities:type_name -> coco.v1.NodeStatus.CapabilitiesEntry
	27, // 2: coco.v1.RegisterNodeRequest.capabilities:type_name -> coco.v1.RegisterNodeRequest.CapabilitiesEntry
	14, // 3: coco.v1.HeartbeatRequest.status:type_name -> coco.v1.NodeStatus
	28, // 4: coco.v1.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	20, // 5: coco.v1.ReportMetricsRequest.metrics:type_name -> coco.v1.Metric
	28, // 6: coco.v1.Metric.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 7: coco.v1.NodeService.BootSandbox:input_type -> coco.v1.BootSandboxRequest
	2,  // 8: coco.v1.NodeService.DestroyVM:input_type -> coco.v1.DestroyVMRequest
	4,  // 9: coco.v1.NodeService.PauseVM:input_type -> coco.v1.PauseVMRequest
	6,  // 10: coco.v1.NodeService.ResumeVM:input_type -> coco.v1.ResumeVMRequest
	8,  // 11: coco.v1.NodeService.ForkVM:input_type -> coco.v1.ForkVMRequest
	10, // 12: coco.v1.NodeService.ExecVM:input_type -> coco.v1.ExecVMRequest
	12, // 13: coco.v1.NodeService.StreamingExecVM:input_type -> coco.v1.StreamingExecVMRequest
	13, // 14: coco.v1.NodeService.GetNodeStatus:input_type -> coco.v1.GetNodeStatusRequest
	15, // 15: coco.v1.NodeService.RegisterNode:input_type -> coco.v1.RegisterNodeRequest
	17, // 16: coco.v1.NodeService.Heartbeat:input_type -> coco.v1.HeartbeatRequest
	19, // 17: coco.v1.NodeService.ReportMetrics:input_type -> coco.v1.ReportMetricsRequest
	22, // 18: coco.v1.NodeService.GetPoolStatus:input_type -> coco.v1.GetPoolStatusRequest
	24, // 19: coco.v1.NodeService.PrewarmPool:input_type -> coco.v1.PrewarmPoolRequest
	1,  // 20: coco.v1.NodeService.BootSandbox:output_type -> coco.v1.BootSandboxResponse
	3,  // 21: coco.v1.NodeService.DestroyVM:output_type -> coco.v1.DestroyVMResponse
	5,  // 22: coco.v1.NodeService.PauseVM:output_type -> coco.v1.PauseVMResponse
	7,  // 23: coco.v1.NodeService.ResumeVM:output_type -> coco.v1.ResumeVMResponse
	9,  // 24: coco.v1.NodeService.ForkVM:output_type -> coco.v1.ForkVMResponse
	11, // 25: coco.v1.NodeService.ExecVM:output_type -> coco.v1.ExecVMResponse
	29, // 26: coco.v1.NodeService.StreamingExecVM:output_type -> coco.v1.ExecChunk
	14, // 27: coco.v1.NodeService.GetNodeStatus:output_type -> coco.v1.NodeStatus
	16, // 28: coco.v1.NodeService.RegisterNode:output_type -> coco.v1.RegisterNodeResponse
	18, // 29: coco.v1.NodeService.Heartbeat:output_type -> coco.v1.HeartbeatResponse
	21, // 30: coco.v1.NodeService.ReportMetrics:output_type -> coco.v1.ReportMetricsResponse
	23, // 31: coco.v1.NodeService.GetPoolStatus:output_type -> coco.v1.PoolStatus
	25, // 32: coco.v1.NodeService.PrewarmPool:output_type -> coco.v1.PrewarmPoolResponse
	20, // [20:33] is the sub-list for method output_type
	7,  // [7:20] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_coco_v1_node_proto_init() }
func file_proto_coco_v1_node_proto_init() {
	if File_proto_coco_v1_node_proto != nil {
		return
	}
	file_proto_coco_v1_coco_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coco_v1_node_proto_rawDesc), len(file_proto_coco_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coco_v1_node_proto_goTypes,
		DependencyIndexes: file_proto_coco_v1_node_proto_depIdxs,
		MessageInfos:      file_proto_coco_v1_node_proto_msgTypes,
	}.Build()
	File_proto_coco_v1_node_proto = out.File
	file_proto_coco_v1_node_proto_goTypes = nil
	file_proto_coco_v1_node_proto_depIdxs = nil
}
