// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/coco/v1/coco.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/coco-sandbox/coco/pkg/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GatewayServiceName is the fully-qualified name of the GatewayService service.
	GatewayServiceName = "coco.v1.GatewayService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GatewayServiceCreateSandboxProcedure is the fully-qualified name of the GatewayService's
	// CreateSandbox RPC.
	GatewayServiceCreateSandboxProcedure = "/coco.v1.GatewayService/CreateSandbox"
	// GatewayServiceGetSandboxProcedure is the fully-qualified name of the GatewayService's GetSandbox
	// RPC.
	GatewayServiceGetSandboxProcedure = "/coco.v1.GatewayService/GetSandbox"
	// GatewayServiceListSandboxesProcedure is the fully-qualified name of the GatewayService's
	// ListSandboxes RPC.
	GatewayServiceListSandboxesProcedure = "/coco.v1.GatewayService/ListSandboxes"
	// GatewayServiceDeleteSandboxProcedure is the fully-qualified name of the GatewayService's
	// DeleteSandbox RPC.
	GatewayServiceDeleteSandboxProcedure = "/coco.v1.GatewayService/DeleteSandbox"
	// GatewayServicePauseSandboxProcedure is the fully-qualified name of the GatewayService's
	// PauseSandbox RPC.
	GatewayServicePauseSandboxProcedure = "/coco.v1.GatewayService/PauseSandbox"
	// GatewayServiceResumeSandboxProcedure is the fully-qualified name of the GatewayService's
	// ResumeSandbox RPC.
	GatewayServiceResumeSandboxProcedure = "/coco.v1.GatewayService/ResumeSandbox"
	// GatewayServiceForkSandboxProcedure is the fully-qualified name of the GatewayService's
	// ForkSandbox RPC.
	GatewayServiceForkSandboxProcedure = "/coco.v1.GatewayService/ForkSandbox"
	// GatewayServiceHibernateSandboxProcedure is the fully-qualified name of the GatewayService's
	// HibernateSandbox RPC.
	GatewayServiceHibernateSandboxProcedure = "/coco.v1.GatewayService/HibernateSandbox"
	// GatewayServiceRestoreSandboxProcedure is the fully-qualified name of the GatewayService's
	// RestoreSandbox RPC.
	GatewayServiceRestoreSandboxProcedure = "/coco.v1.GatewayService/RestoreSandbox"
	// GatewayServiceExecProcedure is the fully-qualified name of the GatewayService's Exec RPC.
	GatewayServiceExecProcedure = "/coco.v1.GatewayService/Exec"
	// GatewayServiceStreamingExecProcedure is the fully-qualified name of the GatewayService's
	// StreamingExec RPC.
	GatewayServiceStreamingExecProcedure = "/coco.v1.GatewayService/StreamingExec"
	// GatewayServiceCreateTemplateProcedure is the fully-qualified name of the GatewayService's
	// CreateTemplate RPC.
	GatewayServiceCreateTemplateProcedure = "/coco.v1.GatewayService/CreateTemplate"
	// GatewayServiceGetTemplateProcedure is the fully-qualified name of the GatewayService's
	// GetTemplate RPC.
	GatewayServiceGetTemplateProcedure = "/coco.v1.GatewayService/GetTemplate"
	// GatewayServiceListTemplatesProcedure is the fully-qualified name of the GatewayService's
	// ListTemplates RPC.
	GatewayServiceListTemplatesProcedure = "/coco.v1.GatewayService/ListTemplates"
	// GatewayServiceDeleteTemplateProcedure is the fully-qualified name of the GatewayService's
	// DeleteTemplate RPC.
	GatewayServiceDeleteTemplateProcedure = "/coco.v1.GatewayService/DeleteTemplate"
	// GatewayServiceBuildTemplateProcedure is the fully-qualified name of the GatewayService's
	// BuildTemplate RPC.
	GatewayServiceBuildTemplateProcedure = "/coco.v1.GatewayService/BuildTemplate"
	// GatewayServiceGetClusterInfoProcedure is the fully-qualified name of the GatewayService's
	// GetClusterInfo RPC.
	GatewayServiceGetClusterInfoProcedure = "/coco.v1.GatewayService/GetClusterInfo"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	gatewayServiceServiceDescriptor                = v1.File_proto_coco_v1_coco_proto.Services().ByName("GatewayService")
	gatewayServiceCreateSandboxMethodDescriptor    = gatewayServiceServiceDescriptor.Methods().ByName("CreateSandbox")
	gatewayServiceGetSandboxMethodDescriptor       = gatewayServiceServiceDescriptor.Methods().ByName("GetSandbox")
	gatewayServiceListSandboxesMethodDescriptor    = gatewayServiceServiceDescriptor.Methods().ByName("ListSandboxes")
	gatewayServiceDeleteSandboxMethodDescriptor    = gatewayServiceServiceDescriptor.Methods().ByName("DeleteSandbox")
	gatewayServicePauseSandboxMethodDescriptor     = gatewayServiceServiceDescriptor.Methods().ByName("PauseSandbox")
	gatewayServiceResumeSandboxMethodDescriptor    = gatewayServiceServiceDescriptor.Methods().ByName("ResumeSandbox")
	gatewayServiceForkSandboxMethodDescriptor      = gatewayServiceServiceDescriptor.Methods().ByName("ForkSandbox")
	gatewayServiceHibernateSandboxMethodDescriptor = gatewayServiceServiceDescriptor.Methods().ByName("HibernateSandbox")
	gatewayServiceRestoreSandboxMethodDescriptor   = gatewayServiceServiceDescriptor.Methods().ByName("RestoreSandbox")
	gatewayServiceExecMethodDescriptor             = gatewayServiceServiceDescriptor.Methods().ByName("Exec")
	gatewayServiceStreamingExecMethodDescriptor    = gatewayServiceServiceDescriptor.Methods().ByName("StreamingExec")
	gatewayServiceCreateTemplateMethodDescriptor   = gatewayServiceServiceDescriptor.Methods().ByName("CreateTemplate")
	gatewayServiceGetTemplateMethodDescriptor      = gatewayServiceServiceDescriptor.Methods().ByName("GetTemplate")
	gatewayServiceListTemplatesMethodDescriptor    = gatewayServiceServiceDescriptor.Methods().ByName("ListTemplates")
	gatewayServiceDeleteTemplateMethodDescriptor   = gatewayServiceServiceDescriptor.Methods().ByName("DeleteTemplate")
	gatewayServiceBuildTemplateMethodDescriptor    = gatewayServiceServiceDescriptor.Methods().ByName("BuildTemplate")
	gatewayServiceGetClusterInfoMethodDescriptor   = gatewayServiceServiceDescriptor.Methods().ByName("GetClusterInfo")
)

// GatewayServiceClient is a client for the coco.v1.GatewayService service.
type GatewayServiceClient interface {
	// Sandbox lifecycle
	CreateSandbox(context.Context, *connect.Request[v1.CreateSandboxRequest]) (*connect.Response[v1.CreateSandboxResponse], error)
	GetSandbox(context.Context, *connect.Request[v1.GetSandboxRequest]) (*connect.Response[v1.GetSandboxResponse], error)
	ListSandboxes(context.Context, *connect.Request[v1.ListSandboxesRequest]) (*connect.Response[v1.ListSandboxesResponse], error)
	DeleteSandbox(context.Context, *connect.Request[v1.DeleteSandboxRequest]) (*connect.Response[v1.DeleteSandboxResponse], error)
	// Sandbox control
	PauseSandbox(context.Context, *connect.Request[v1.PauseSandboxRequest]) (*connect.Response[v1.PauseSandboxResponse], error)
	ResumeSandbox(context.Context, *connect.Request[v1.ResumeSandboxRequest]) (*connect.Response[v1.ResumeSandboxResponse], error)
	ForkSandbox(context.Context, *connect.Request[v1.ForkSandboxRequest]) (*connect.Response[v1.ForkSandboxResponse], error)
	HibernateSandbox(context.Context, *connect.Request[v1.HibernateSandboxRequest]) (*connect.Response[v1.HibernateSandboxResponse], error)
	RestoreSandbox(context.Context, *connect.Request[v1.RestoreSandboxRequest]) (*connect.Response[v1.RestoreSandboxResponse], error)
	// Execution
	Exec(context.Context, *connect.Request[v1.ExecRequest]) (*connect.Response[v1.ExecResponse], error)
	StreamingExec(context.Context, *connect.Request[v1.StreamingExecRequest]) (*connect.ServerStreamForClient[v1.ExecChunk], error)
	// Templates
	CreateTemplate(context.Context, *connect.Request[v1.CreateTemplateRequest]) (*connect.Response[v1.CreateTemplateResponse], error)
	GetTemplate(context.Context, *connect.Request[v1.GetTemplateRequest]) (*connect.Response[v1.GetTemplateResponse], error)
	ListTemplates(context.Context, *connect.Request[v1.ListTemplatesRequest]) (*connect.Response[v1.ListTemplatesResponse], error)
	DeleteTemplate(context.Context, *connect.Request[v1.DeleteTemplateRequest]) (*connect.Response[v1.DeleteTemplateResponse], error)
	BuildTemplate(context.Context, *connect.Request[v1.BuildTemplateRequest]) (*connect.Response[v1.BuildTemplateResponse], error)
	// Cluster
	GetClusterInfo(context.Context, *connect.Request[v1.GetClusterInfoRequest]) (*connect.Response[v1.GetClusterInfoResponse], error)
}

// NewGatewayServiceClient constructs a client for the coco.v1.GatewayService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGatewayServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GatewayServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &gatewayServiceClient{
		createSandbox: connect.NewClient[v1.CreateSandboxRequest, v1.CreateSandboxResponse](
			httpClient,
			baseURL+GatewayServiceCreateSandboxProcedure,
			connect.WithSchema(gatewayServiceCreateSandboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSandbox: connect.NewClient[v1.GetSandboxRequest, v1.GetSandboxResponse](
			httpClient,
			baseURL+GatewayServiceGetSandboxProcedure,
			connect.WithSchema(gatewayServiceGetSandboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listSandboxes: connect.NewClient[v1.ListSandboxesRequest, v1.ListSandboxesResponse](
			httpClient,
			baseURL+GatewayServiceListSandboxesProcedure,
			connect.WithSchema(gatewayServiceListSandboxesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteSandbox: connect.NewClient[v1.DeleteSandboxRequest, v1.DeleteSandboxResponse](
			httpClient,
			baseURL+GatewayServiceDeleteSandboxProcedure,
			connect.WithSchema(gatewayServiceDeleteSandboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		pauseSandbox: connect.NewClient[v1.PauseSandboxRequest, v1.PauseSandboxResponse](
			httpClient,
			baseURL+GatewayServicePauseSandboxProcedure,
			connect.WithSchema(gatewayServicePauseSandboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		resumeSandbox: connect.NewClient[v1.ResumeSandboxRequest, v1.ResumeSandboxResponse](
			httpClient,
			baseURL+GatewayServiceResumeSandboxProcedure,
			connect.WithSchema(gatewayServiceResumeSandboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		forkSandbox: connect.NewClient[v1.ForkSandboxRequest, v1.ForkSandboxResponse](
			httpClient,
			baseURL+GatewayServiceForkSandboxProcedure,
			connect.WithSchema(gatewayServiceForkSandboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		hibernateSandbox: connect.NewClient[v1.HibernateSandboxRequest, v1.HibernateSandboxResponse](
			httpClient,
			baseURL+GatewayServiceHibernateSandboxProcedure,
			connect.WithSchema(gatewayServiceHibernateSandboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		restoreSandbox: connect.NewClient[v1.RestoreSandboxRequest, v1.RestoreSandboxResponse](
			httpClient,
			baseURL+GatewayServiceRestoreSandboxProcedure,
			connect.WithSchema(gatewayServiceRestoreSandboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		exec: connect.NewClient[v1.ExecRequest, v1.ExecResponse](
			httpClient,
			baseURL+GatewayServiceExecProcedure,
			connect.WithSchema(gatewayServiceExecMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		streamingExec: connect.NewClient[v1.StreamingExecRequest, v1.ExecChunk](
			httpClient,
			baseURL+GatewayServiceStreamingExecProcedure,
			connect.WithSchema(gatewayServiceStreamingExecMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createTemplate: connect.NewClient[v1.CreateTemplateRequest, v1.CreateTemplateResponse](
			httpClient,
			baseURL+GatewayServiceCreateTemplateProcedure,
			connect.WithSchema(gatewayServiceCreateTemplateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getTemplate: connect.NewClient[v1.GetTemplateRequest, v1.GetTemplateResponse](
			httpClient,
			baseURL+GatewayServiceGetTemplateProcedure,
			connect.WithSchema(gatewayServiceGetTemplateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listTemplates: connect.NewClient[v1.ListTemplatesRequest, v1.ListTemplatesResponse](
			httpClient,
			baseURL+GatewayServiceListTemplatesProcedure,
			connect.WithSchema(gatewayServiceListTemplatesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteTemplate: connect.NewClient[v1.DeleteTemplateRequest, v1.DeleteTemplateResponse](
			httpClient,
			baseURL+GatewayServiceDeleteTemplateProcedure,
			connect.WithSchema(gatewayServiceDeleteTemplateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		buildTemplate: connect.NewClient[v1.BuildTemplateRequest, v1.BuildTemplateResponse](
			httpClient,
			baseURL+GatewayServiceBuildTemplateProcedure,
			connect.WithSchema(gatewayServiceBuildTemplateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getClusterInfo: connect.NewClient[v1.GetClusterInfoRequest, v1.GetClusterInfoResponse](
			httpClient,
			baseURL+GatewayServiceGetClusterInfoProcedure,
			connect.WithSchema(gatewayServiceGetClusterInfoMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// gatewayServiceClient implements GatewayServiceClient.
type gatewayServiceClient struct {
	createSandbox    *connect.Client[v1.CreateSandboxRequest, v1.CreateSandboxResponse]
	getSandbox       *connect.Client[v1.GetSandboxRequest, v1.GetSandboxResponse]
	listSandboxes    *connect.Client[v1.ListSandboxesRequest, v1.ListSandboxesResponse]
	deleteSandbox    *connect.Client[v1.DeleteSandboxRequest, v1.DeleteSandboxResponse]
	pauseSandbox     *connect.Client[v1.PauseSandboxRequest, v1.PauseSandboxResponse]
	resumeSandbox    *connect.Client[v1.ResumeSandboxRequest, v1.ResumeSandboxResponse]
	forkSandbox      *connect.Client[v1.ForkSandboxRequest, v1.ForkSandboxResponse]
	hibernateSandbox *connect.Client[v1.HibernateSandboxRequest, v1.HibernateSandboxResponse]
	restoreSandbox   *connect.Client[v1.RestoreSandboxRequest, v1.RestoreSandboxResponse]
	exec             *connect.Client[v1.ExecRequest, v1.ExecResponse]
	streamingExec    *connect.Client[v1.StreamingExecRequest, v1.ExecChunk]
	createTemplate   *connect.Client[v1.CreateTemplateRequest, v1.CreateTemplateResponse]
	getTemplate      *connect.Client[v1.GetTemplateRequest, v1.GetTemplateResponse]
	listTemplates    *connect.Client[v1.ListTemplatesRequest, v1.ListTemplatesResponse]
	deleteTemplate   *connect.Client[v1.DeleteTemplateRequest, v1.DeleteTemplateResponse]
	buildTemplate    *connect.Client[v1.BuildTemplateRequest, v1.BuildTemplateResponse]
	getClusterInfo   *connect.Client[v1.GetClusterInfoRequest, v1.GetClusterInfoResponse]
}

// CreateSandbox calls coco.v1.GatewayService.CreateSandbox.
func (c *gatewayServiceClient) CreateSandbox(ctx context.Context, req *connect.Request[v1.CreateSandboxRequest]) (*connect.Response[v1.CreateSandboxResponse], error) {
	return c.createSandbox.CallUnary(ctx, req)
}

// GetSandbox calls coco.v1.GatewayService.GetSandbox.
func (c *gatewayServiceClient) GetSandbox(ctx context.Context, req *connect.Request[v1.GetSandboxRequest]) (*connect.Response[v1.GetSandboxResponse], error) {
	return c.getSandbox.CallUnary(ctx, req)
}

// ListSandboxes calls coco.v1.GatewayService.ListSandboxes.
func (c *gatewayServiceClient) ListSandboxes(ctx context.Context, req *connect.Request[v1.ListSandboxesRequest]) (*connect.Response[v1.ListSandboxesResponse], error) {
	return c.listSandboxes.CallUnary(ctx, req)
}

// DeleteSandbox calls coco.v1.GatewayService.DeleteSandbox.
func (c *gatewayServiceClient) DeleteSandbox(ctx context.Context, req *connect.Request[v1.DeleteSandboxRequest]) (*connect.Response[v1.DeleteSandboxResponse], error) {
	return c.deleteSandbox.CallUnary(ctx, req)
}

// PauseSandbox calls coco.v1.GatewayService.PauseSandbox.
func (c *gatewayServiceClient) PauseSandbox(ctx context.Context, req *connect.Request[v1.PauseSandboxRequest]) (*connect.Response[v1.PauseSandboxResponse], error) {
	return c.pauseSandbox.CallUnary(ctx, req)
}

// ResumeSandbox calls coco.v1.GatewayService.ResumeSandbox.
func (c *gatewayServiceClient) ResumeSandbox(ctx context.Context, req *connect.Request[v1.ResumeSandboxRequest]) (*connect.Response[v1.ResumeSandboxResponse], error) {
	return c.resumeSandbox.CallUnary(ctx, req)
}

// ForkSandbox calls coco.v1.GatewayService.ForkSandbox.
func (c *gatewayServiceClient) ForkSandbox(ctx context.Context, req *connect.Request[v1.ForkSandboxRequest]) (*connect.Response[v1.ForkSandboxResponse], error) {
	return c.forkSandbox.CallUnary(ctx, req)
}

// HibernateSandbox calls coco.v1.GatewayService.HibernateSandbox.
func (c *gatewayServiceClient) HibernateSandbox(ctx context.Context, req *connect.Request[v1.HibernateSandboxRequest]) (*connect.Response[v1.HibernateSandboxResponse], error) {
	return c.hibernateSandbox.CallUnary(ctx, req)
}

// RestoreSandbox calls coco.v1.GatewayService.RestoreSandbox.
func (c *gatewayServiceClient) RestoreSandbox(ctx context.Context, req *connect.Request[v1.RestoreSandboxRequest]) (*connect.Response[v1.RestoreSandboxResponse], error) {
	return c.restoreSandbox.CallUnary(ctx, req)
}

// Exec calls coco.v1.GatewayService.Exec.
func (c *gatewayServiceClient) Exec(ctx context.Context, req *connect.Request[v1.ExecRequest]) (*connect.Response[v1.ExecResponse], error) {
	return c.exec.CallUnary(ctx, req)
}

// StreamingExec calls coco.v1.GatewayService.StreamingExec.
func (c *gatewayServiceClient) StreamingExec(ctx context.Context, req *connect.Request[v1.StreamingExecRequest]) (*connect.ServerStreamForClient[v1.ExecChunk], error) {
	return c.streamingExec.CallServerStream(ctx, req)
}

// CreateTemplate calls coco.v1.GatewayService.CreateTemplate.
func (c *gatewayServiceClient) CreateTemplate(ctx context.Context, req *connect.Request[v1.CreateTemplateRequest]) (*connect.Response[v1.CreateTemplateResponse], error) {
	return c.createTemplate.CallUnary(ctx, req)
}

// GetTemplate calls coco.v1.GatewayService.GetTemplate.
func (c *gatewayServiceClient) GetTemplate(ctx context.Context, req *connect.Request[v1.GetTemplateRequest]) (*connect.Response[v1.GetTemplateResponse], error) {
	return c.getTemplate.CallUnary(ctx, req)
}

// ListTemplates calls coco.v1.GatewayService.ListTemplates.
func (c *gatewayServiceClient) ListTemplates(ctx context.Context, req *connect.Request[v1.ListTemplatesRequest]) (*connect.Response[v1.ListTemplatesResponse], error) {
	return c.listTemplates.CallUnary(ctx, req)
}

// DeleteTemplate calls coco.v1.GatewayService.DeleteTemplate.
func (c *gatewayServiceClient) DeleteTemplate(ctx context.Context, req *connect.Request[v1.DeleteTemplateRequest]) (*connect.Response[v1.DeleteTemplateResponse], error) {
	return c.deleteTemplate.CallUnary(ctx, req)
}

// BuildTemplate calls coco.v1.GatewayService.BuildTemplate.
func (c *gatewayServiceClient) BuildTemplate(ctx context.Context, req *connect.Request[v1.BuildTemplateRequest]) (*connect.Response[v1.BuildTemplateResponse], error) {
	return c.buildTemplate.CallUnary(ctx, req)
}

// GetClusterInfo calls coco.v1.GatewayService.GetClusterInfo.
func (c *gatewayServiceClient) GetClusterInfo(ctx context.Context, req *connect.Request[v1.GetClusterInfoRequest]) (*connect.Response[v1.GetClusterInfoResponse], error) {
	return c.getClusterInfo.CallUnary(ctx, req)
}

// GatewayServiceHandler is an implementation of the coco.v1.GatewayService service.
type GatewayServiceHandler interface {
	// Sandbox lifecycle
	CreateSandbox(context.Context, *connect.Request[v1.CreateSandboxRequest]) (*connect.Response[v1.CreateSandboxResponse], error)
	GetSandbox(context.Context, *connect.Request[v1.GetSandboxRequest]) (*connect.Response[v1.GetSandboxResponse], error)
	ListSandboxes(context.Context, *connect.Request[v1.ListSandboxesRequest]) (*connect.Response[v1.ListSandboxesResponse], error)
	DeleteSandbox(context.Context, *connect.Request[v1.DeleteSandboxRequest]) (*connect.Response[v1.DeleteSandboxResponse], error)
	// Sandbox control
	PauseSandbox(context.Context, *connect.Request[v1.PauseSandboxRequest]) (*connect.Response[v1.PauseSandboxResponse], error)
	ResumeSandbox(context.Context, *connect.Request[v1.ResumeSandboxRequest]) (*connect.Response[v1.ResumeSandboxResponse], error)
	ForkSandbox(context.Context, *connect.Request[v1.ForkSandboxRequest]) (*connect.Response[v1.ForkSandboxResponse], error)
	HibernateSandbox(context.Context, *connect.Request[v1.HibernateSandboxRequest]) (*connect.Response[v1.HibernateSandboxResponse], error)
	RestoreSandbox(context.Context, *connect.Request[v1.RestoreSandboxRequest]) (*connect.Response[v1.RestoreSandboxResponse], error)
	// Execution
	Exec(context.Context, *connect.Request[v1.ExecRequest]) (*connect.Response[v1.ExecResponse], error)
	StreamingExec(context.Context, *connect.Request[v1.StreamingExecRequest], *connect.ServerStream[v1.ExecChunk]) error
	// Templates
	CreateTemplate(context.Context, *connect.Request[v1.CreateTemplateRequest]) (*connect.Response[v1.CreateTemplateResponse], error)
	GetTemplate(context.Context, *connect.Request[v1.GetTemplateRequest]) (*connect.Response[v1.GetTemplateResponse], error)
	ListTemplates(context.Context, *connect.Request[v1.ListTemplatesRequest]) (*connect.Response[v1.ListTemplatesResponse], error)
	DeleteTemplate(context.Context, *connect.Request[v1.DeleteTemplateRequest]) (*connect.Response[v1.DeleteTemplateResponse], error)
	BuildTemplate(context.Context, *connect.Request[v1.BuildTemplateRequest]) (*connect.Response[v1.BuildTemplateResponse], error)
	// Cluster
	GetClusterInfo(context.Context, *connect.Request[v1.GetClusterInfoRequest]) (*connect.Response[v1.GetClusterInfoResponse], error)
}

// NewGatewayServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGatewayServiceHandler(svc GatewayServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gatewayServiceCreateSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceCreateSandboxProcedure,
		svc.CreateSandbox,
		connect.WithSchema(gatewayServiceCreateSandboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceGetSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceGetSandboxProcedure,
		svc.GetSandbox,
		connect.WithSchema(gatewayServiceGetSandboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceListSandboxesHandler := connect.NewUnaryHandler(
		GatewayServiceListSandboxesProcedure,
		svc.ListSandboxes,
		connect.WithSchema(gatewayServiceListSandboxesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceDeleteSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceDeleteSandboxProcedure,
		svc.DeleteSandbox,
		connect.WithSchema(gatewayServiceDeleteSandboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServicePauseSandboxHandler := connect.NewUnaryHandler(
		GatewayServicePauseSandboxProcedure,
		svc.PauseSandbox,
		connect.WithSchema(gatewayServicePauseSandboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceResumeSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceResumeSandboxProcedure,
		svc.ResumeSandbox,
		connect.WithSchema(gatewayServiceResumeSandboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceForkSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceForkSandboxProcedure,
		svc.ForkSandbox,
		connect.WithSchema(gatewayServiceForkSandboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceHibernateSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceHibernateSandboxProcedure,
		svc.HibernateSandbox,
		connect.WithSchema(gatewayServiceHibernateSandboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceRestoreSandboxHandler := connect.NewUnaryHandler(
		GatewayServiceRestoreSandboxProcedure,
		svc.RestoreSandbox,
		connect.WithSchema(gatewayServiceRestoreSandboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceExecHandler := connect.NewUnaryHandler(
		GatewayServiceExecProcedure,
		svc.Exec,
		connect.WithSchema(gatewayServiceExecMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceStreamingExecHandler := connect.NewServerStreamHandler(
		GatewayServiceStreamingExecProcedure,
		svc.StreamingExec,
		connect.WithSchema(gatewayServiceStreamingExecMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceCreateTemplateHandler := connect.NewUnaryHandler(
		GatewayServiceCreateTemplateProcedure,
		svc.CreateTemplate,
		connect.WithSchema(gatewayServiceCreateTemplateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceGetTemplateHandler := connect.NewUnaryHandler(
		GatewayServiceGetTemplateProcedure,
		svc.GetTemplate,
		connect.WithSchema(gatewayServiceGetTemplateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceListTemplatesHandler := connect.NewUnaryHandler(
		GatewayServiceListTemplatesProcedure,
		svc.ListTemplates,
		connect.WithSchema(gatewayServiceListTemplatesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceDeleteTemplateHandler := connect.NewUnaryHandler(
		GatewayServiceDeleteTemplateProcedure,
		svc.DeleteTemplate,
		connect.WithSchema(gatewayServiceDeleteTemplateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceBuildTemplateHandler := connect.NewUnaryHandler(
		GatewayServiceBuildTemplateProcedure,
		svc.BuildTemplate,
		connect.WithSchema(gatewayServiceBuildTemplateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceGetClusterInfoHandler := connect.NewUnaryHandler(
		GatewayServiceGetClusterInfoProcedure,
		svc.GetClusterInfo,
		connect.WithSchema(gatewayServiceGetClusterInfoMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/coco.v1.GatewayService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GatewayServiceCreateSandboxProcedure:
			gatewayServiceCreateSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceGetSandboxProcedure:
			gatewayServiceGetSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceListSandboxesProcedure:
			gatewayServiceListSandboxesHandler.ServeHTTP(w, r)
		case GatewayServiceDeleteSandboxProcedure:
			gatewayServiceDeleteSandboxHandler.ServeHTTP(w, r)
		case GatewayServicePauseSandboxProcedure:
			gatewayServicePauseSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceResumeSandboxProcedure:
			gatewayServiceResumeSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceForkSandboxProcedure:
			gatewayServiceForkSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceHibernateSandboxProcedure:
			gatewayServiceHibernateSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceRestoreSandboxProcedure:
			gatewayServiceRestoreSandboxHandler.ServeHTTP(w, r)
		case GatewayServiceExecProcedure:
			gatewayServiceExecHandler.ServeHTTP(w, r)
		case GatewayServiceStreamingExecProcedure:
			gatewayServiceStreamingExecHandler.ServeHTTP(w, r)
		case GatewayServiceCreateTemplateProcedure:
			gatewayServiceCreateTemplateHandler.ServeHTTP(w, r)
		case GatewayServiceGetTemplateProcedure:
			gatewayServiceGetTemplateHandler.ServeHTTP(w, r)
		case GatewayServiceListTemplatesProcedure:
			gatewayServiceListTemplatesHandler.ServeHTTP(w, r)
		case GatewayServiceDeleteTemplateProcedure:
			gatewayServiceDeleteTemplateHandler.ServeHTTP(w, r)
		case GatewayServiceBuildTemplateProcedure:
			gatewayServiceBuildTemplateHandler.ServeHTTP(w, r)
		case GatewayServiceGetClusterInfoProcedure:
			gatewayServiceGetClusterInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGatewayServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGatewayServiceHandler struct{}

func (UnimplementedGatewayServiceHandler) CreateSandbox(context.Context, *connect.Request[v1.CreateSandboxRequest]) (*connect.Response[v1.CreateSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.CreateSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) GetSandbox(context.Context, *connect.Request[v1.GetSandboxRequest]) (*connect.Response[v1.GetSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.GetSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ListSandboxes(context.Context, *connect.Request[v1.ListSandboxesRequest]) (*connect.Response[v1.ListSandboxesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.ListSandboxes is not implemented"))
}

func (UnimplementedGatewayServiceHandler) DeleteSandbox(context.Context, *connect.Request[v1.DeleteSandboxRequest]) (*connect.Response[v1.DeleteSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.DeleteSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) PauseSandbox(context.Context, *connect.Request[v1.PauseSandboxRequest]) (*connect.Response[v1.PauseSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.PauseSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ResumeSandbox(context.Context, *connect.Request[v1.ResumeSandboxRequest]) (*connect.Response[v1.ResumeSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.ResumeSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ForkSandbox(context.Context, *connect.Request[v1.ForkSandboxRequest]) (*connect.Response[v1.ForkSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.ForkSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) HibernateSandbox(context.Context, *connect.Request[v1.HibernateSandboxRequest]) (*connect.Response[v1.HibernateSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.HibernateSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) RestoreSandbox(context.Context, *connect.Request[v1.RestoreSandboxRequest]) (*connect.Response[v1.RestoreSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.RestoreSandbox is not implemented"))
}

func (UnimplementedGatewayServiceHandler) Exec(context.Context, *connect.Request[v1.ExecRequest]) (*connect.Response[v1.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.Exec is not implemented"))
}

func (UnimplementedGatewayServiceHandler) StreamingExec(context.Context, *connect.Request[v1.StreamingExecRequest], *connect.ServerStream[v1.ExecChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.StreamingExec is not implemented"))
}

func (UnimplementedGatewayServiceHandler) CreateTemplate(context.Context, *connect.Request[v1.CreateTemplateRequest]) (*connect.Response[v1.CreateTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.CreateTemplate is not implemented"))
}

func (UnimplementedGatewayServiceHandler) GetTemplate(context.Context, *connect.Request[v1.GetTemplateRequest]) (*connect.Response[v1.GetTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.GetTemplate is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ListTemplates(context.Context, *connect.Request[v1.ListTemplatesRequest]) (*connect.Response[v1.ListTemplatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.ListTemplates is not implemented"))
}

func (UnimplementedGatewayServiceHandler) DeleteTemplate(context.Context, *connect.Request[v1.DeleteTemplateRequest]) (*connect.Response[v1.DeleteTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.DeleteTemplate is not implemented"))
}

func (UnimplementedGatewayServiceHandler) BuildTemplate(context.Context, *connect.Request[v1.BuildTemplateRequest]) (*connect.Response[v1.BuildTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.BuildTemplate is not implemented"))
}

func (UnimplementedGatewayServiceHandler) GetClusterInfo(context.Context, *connect.Request[v1.GetClusterInfoRequest]) (*connect.Response[v1.GetClusterInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coco.v1.GatewayService.GetClusterInfo is not implemented"))
}
