const std = @import("std");
const linux = std.os.linux;

const SCMP_SYSNO = c"scmp_syscall_num_t";
const SCMP_CMP = c"scmp_arg_cmp";

const SECCOMP_MODE_FILTER = 2;
const SECCOMP_RET_ALLOW = 0x7fff0000;
const SECCOMP_RET_KILL = 0x00000000;
const SECCOMP_RET_KILL_THREAD = 0x00000000;
const SECCOMP_RET_KILL_PROCESS = 0x80000000;
const SECCOMP_RET_TRAP = 0x00030000;
const SECCOMP_RET_ERRNO = 0x00050000;
const SECCOMP_RET_TRACE = 0x7ff00000;

const PR_SET_SECCOMP = 22;
const PR_GET_SECCOMP = 21;

extern "c" fn seccomp(user_compat: c_int, flags: c_uint, data: ?*anyopaque) callconv(.C) c_int;

const sock_filter = extern struct {
    code: u16,
    jt: u8,
    jf: u8,
    k: u32,
};

const sock_fprog = extern struct {
    len: c_ushort,
    filter: [*]sock_filter,
};

pub const ScmpCompare = enum(c_int) {
    NE = 1,
    LT = 2,
    LE = 3,
    EQ = 4,
    GE = 5,
    GT = 6,
    MASKED_EQ = 7,
};

pub const ScmpAction = enum(c_int) {
    KILL = SECCOMP_RET_KILL,
    KILL_THREAD = SECCOMP_RET_KILL_THREAD,
    KILL_PROCESS = SECCOMP_RET_KILL_PROCESS,
    TRAP = SECCOMP_RET_TRAP,
    ERRNO = SECCOMP_RET_ERRNO,
    TRACE = SECCOMP_RET_TRACE,
    ALLOW = SECCOMP_RET_ALLOW,
};

pub const ScmpArch = enum(c_int) {
    NATIVE = 0,
    X86 = 1,
    X86_64 = 2,
    X32 = 3,
    ARM = 4,
    AARCH64 = 5,
    MIPS = 6,
    MIPS64 = 7,
    MIPSEL = 8,
    MIPSEL64 = 9,
    PPC64 = 10,
    PPC64LE = 11,
    S390 = 12,
};

pub const Syscall = enum(usize) {
    read = 0,
    write = 1,
    open = 2,
    close = 3,
    stat = 4,
    fstat = 5,
    lstat = 6,
    poll = 7,
    lseek = 8,
    mmap = 9,
    mprotect = 10,
    brk = 11,
    rt_sigaction = 13,
    rt_sigprocmask = 14,
    rt_sigreturn = 15,
    ioctl = 16,
    pread64 = 17,
    pwrite64 = 18,
    readv = 19,
    writev = 20,
    access = 21,
    pipe = 22,
    select = 23,
    sched_yield = 24,
    mremap = 25,
    msync = 26,
    mincore = 27,
    madvise = 28,
    shmget = 29,
    shmat = 30,
    shmctl = 31,
    dup = 32,
    dup2 = 33,
    pause = 34,
    nanosleep = 35,
    getitimer = 36,
    alarm = 37,
    setitimer = 38,
    getpid = 39,
    socket = 40,
    connect = 41,
    accept = 42,
    sendto = 43,
    recvfrom = 44,
    sendmsg = 45,
    recvmsg = 46,
    shutdown = 47,
    bind = 48,
    listen = 49,
    getsockname = 50,
    getpeername = 51,
    socketpair = 52,
    clone = 56,
    fork = 57,
    vfork = 58,
    execve = 59,
    exit = 60,
    wait4 = 61,
    kill = 62,
    uname = 63,
    semget = 64,
    semop = 65,
    semctl = 66,
    shmdt = 67,
    msgget = 68,
    msgsnd = 69,
    msgrcv = 70,
    msgctl = 71,
    fcntl = 72,
    flock = 73,
    fsync = 74,
    fdatasync = 75,
    truncate = 76,
    ftruncate = 77,
    getdents = 78,
    getcwd = 79,
    chdir = 80,
    fchdir = 81,
    rename = 82,
    mkdir = 83,
    rmdir = 84,
    creat = 85,
    link = 86,
    unlink = 87,
    symlink = 88,
    readlink = 89,
    chmod = 90,
    fchmod = 91,
    chown = 92,
    fchown = 93,
    lchown = 94,
    umask = 95,
    gettimeofday = 96,
    getrlimit = 97,
    getrusage = 98,
    sysinfo = 99,
    times = 100,
    ptrace = 101,
    getuid = 102,
    syslog = 103,
    getgid = 104,
    setuid = 105,
    setgid = 106,
    geteuid = 107,
    getegid = 108,
    setpgid = 109,
    getppid = 110,
    getsid = 111,
    setreuid = 112,
    setregid = 113,
    getgroups = 114,
    setgroups = 115,
    setresuid = 116,
    getresuid = 117,
    setresgid = 118,
    getresgid = 119,
    getpgid = 120,
    setfsuid = 121,
    setfsgid = 122,
    getsid = 111,
    capget = 125,
    capset = 126,
    rt_sigpending = 127,
    rt_sigtimedwait = 128,
    rt_sigqueueinfo = 129,
    rt_sigsuspend = 130,
    sigaltstack = 131,
    mknod = 133,
    personality = 136,
    ustat = 138,
    statfs = 140,
    fstatfs = 141,
    sysfs = 142,
    getpriority = 142,
    setpriority = 141,
    sched_setparam = 144,
    sched_getparam = 145,
    sched_setscheduler = 146,
    sched_getscheduler = 147,
    sched_get_priority_max = 148,
    sched_get_priority_min = 149,
    sched_rr_get_interval = 150,
    mlock = 151,
    munlock = 152,
    mlockall = 153,
    munlockall = 154,
    vhangup = 153,
    modify_ldt = 154,
    pivot_root = 155,
    prctl = 157,
    arch_prctl = 158,
    adjtimex = 159,
    setrlimit = 160,
    chroot = 161,
    sync = 162,
    acct = 163,
    settimeofday = 164,
    mount = 165,
    umount2 = 166,
    swapon = 167,
    swapoff = 168,
    reboot = 169,
    setdomainname = 170,
    iopl = 172,
    ioperm = 173,
    init_module = 175,
    delete_module = 176,
    quotactl = 179,
    gettid = 186,
    readahead = 187,
    setxattr = 188,
    lsetxattr = 189,
    fsetxattr = 190,
    getxattr = 191,
    lgetxattr = 192,
    fgetxattr = 193,
    listxattr = 194,
    flistxattr = 195,
    removexattr = 196,
    lremovexattr = 197,
    fremovexattr = 198,
    tkill = 200,
    time = 201,
    futex = 202,
    sched_setaffinity = 203,
    sched_getaffinity = 204,
    io_setup = 206,
    io_destroy = 207,
    io_getevents = 208,
    io_submit = 209,
    io_cancel = 210,
    lookup_dcookie = 211,
    epoll_create = 213,
    remap_file_pages = 216,
    set_tid_address = 218,
    timer_create = 222,
    timer_settime = 223,
    timer_gettime = 224,
    timer_getoverrun = 225,
    timer_delete = 226,
    clock_settime = 227,
    clock_gettime = 228,
    clock_getres = 229,
    clock_nanosleep = 230,
    exit_group = 231,
    epoll_wait = 232,
    epoll_ctl = 233,
    tgkill = 234,
    utimes = 235,
    mbind = 237,
    set_mempolicy = 238,
    get_mempolicy = 239,
    mq_open = 240,
    mq_unlink = 241,
    mq_timedsend = 242,
    mq_timedreceive = 243,
    mq_notify = 244,
    mq_getsetattr = 245,
    kexec_load = 246,
    waitid = 247,
    add_key = 248,
    request_key = 249,
    keyctl = 250,
    ioprio_set = 251,
    ioprio_get = 252,
    inotify_init = 253,
    inotify_add_watch = 254,
    inotify_rm_watch = 255,
    migrate_pages = 256,
    mknodat = 259,
    fchownat = 260,
    futimesat = 261,
    newfstatat = 262,
    unlinkat = 263,
    renameat = 264,
    linkat = 265,
    symlinkat = 266,
    readlinkat = 267,
    fchmodat = 268,
    faccessat = 269,
    pselect6 = 270,
    ppoll = 271,
    unshare = 272,
    splice = 275,
    tee = 276,
    sync_file_range = 277,
    vmsplice = 278,
    move_pages = 279,
    utimensat = 280,
    epoll_pwait = 281,
    signalfd = 282,
    timerfd_create = 283,
    eventfd = 284,
    fallocate = 285,
    timerfd_settime = 286,
    timerfd_gettime = 287,
    accept4 = 288,
    signalfd4 = 289,
    eventfd2 = 290,
    epoll_create1 = 291,
    dup3 = 292,
    pipe2 = 293,
    inotify_init1 = 294,
    preadv = 295,
    pwritev = 296,
    rt_tgsigqueueinfo = 297,
    perf_event_open = 298,
    recvmmsg = 299,
    fanotify_init = 300,
    fanotify_mark = 301,
    prlimit64 = 302,
    name_to_handle_at = 303,
    open_by_handle_at = 304,
    clock_adjtime = 305,
    syncfs = 306,
    sendmmsg = 307,
    setns = 308,
    getcpu = 309,
    process_vm_readv = 310,
    process_vm_writev = 311,
    lookup_dcookie = 211,
    finit_module = 273,
    bpf = 321,
};

const allowed_syscalls = [_]usize{
    @intFromEnum(Syscall.read),
    @intFromEnum(Syscall.write),
    @intFromEnum(Syscall.close),
    @intFromEnum(Syscall.exit),
    @intFromEnum(Syscall.exit_group),
    @intFromEnum(Syscall.readv),
    @intFromEnum(Syscall.writev),
    @intFromEnum(Syscall.brk),
    @intFromEnum(Syscall.mmap),
    @intFromEnum(Syscall.mprotect),
    @intFromEnum(Syscall.clock_gettime),
    @intFromEnum(Syscall.nanosleep),
    @intFromEnum(Syscall.getpid),
    @intFromEnum(Syscall.gettid),
    @intFromEnum(Syscall.getuid),
    @intFromEnum(Syscall.getgid),
    @intFromEnum(Syscall.geteuid),
    @intFromEnum(Syscall.getegid),
    @intFromEnum(Syscall.getppid),
    @intFromEnum(Syscall.getcwd),
    @intFromEnum(Syscall.fstat),
    @intFromEnum(Syscall.fstatfs),
    @intFromEnum(Syscall.ioctl),
    @intFromEnum(Syscall.pread64),
    @intFromEnum(Syscall.pwrite64),
    @intFromEnum(Syscall.access),
    @intFromEnum(Syscall.pipe),
    @intFromEnum(Syscall.select),
    @intFromEnum(Syscall.sched_yield),
    @intFromEnum(Syscall.dup),
    @intFromEnum(Syscall.dup2),
    @intFromEnum(Syscall.dup3),
    @intFromEnum(Syscall.pause),
    @intFromEnum(Syscall.alarm),
    @intFromEnum(Syscall.sleep),
    @intFromEnum(Syscall.uname),
    @intFromEnum(Syscall.getrlimit),
    @intFromEnum(Syscall.getrusage),
    @intFromEnum(Syscall.sysinfo),
    @intFromEnum(Syscall.times),
    @intFromEnum(Syscall.socket),
    @intFromEnum(Syscall.connect),
    @intFromEnum(Syscall.accept),
    @intFromEnum(Syscall.accept4),
    @intFromEnum(Syscall.sendto),
    @intFromEnum(Syscall.recvfrom),
    @intFromEnum(Syscall.sendmsg),
    @intFromEnum(Syscall.recvmsg),
    @intFromEnum(Syscall.shutdown),
    @intFromEnum(Syscall.bind),
    @intFromEnum(Syscall.listen),
    @intFromEnum(Syscall.getsockname),
    @intFromEnum(Syscall.getpeername),
    @intFromEnum(Syscall.socketpair),
    @intFromEnum(Syscall.clone),
    @intFromEnum(Syscall.fork),
    @intFromEnum(Syscall.vfork),
    @intFromEnum(Syscall.execve),
    @intFromEnum(Syscall.wait4),
    @intFromEnum(Syscall.kill),
    @intFromEnum(Syscall.unlink),
    @intFromEnum(Syscall.mkdir),
    @intFromEnum(Syscall.rmdir),
    @intFromEnum(Syscall.creat),
    @intFromEnum(Syscall.link),
    @intFromEnum(Syscall.symlink),
    @intFromEnum(Syscall.readlink),
    @intFromEnum(Syscall.chmod),
    @intFromEnum(Syscall.fchmod),
    @intFromEnum(Syscall.chown),
    @intFromEnum(Syscall.fchown),
    @intFromEnum(Syscall.lchown),
    @intFromEnum(Syscall.umask),
    @intFromEnum(Syscall.gettimeofday),
    @intFromEnum(Syscall.getgroups),
    @intFromEnum(Syscall.setgroups),
    @intFromEnum(Syscall.setresuid),
    @intFromEnum(Syscall.getresuid),
    @intFromEnum(Syscall.setresgid),
    @intFromEnum(Syscall.getresgid),
    @intFromEnum(Syscall.getpgid),
    @intFromEnum(Syscall.setfsuid),
    @intFromEnum(Syscall.setfsgid),
    @intFromEnum(Syscall.getsid),
    @intFromEnum(Syscall.setrlimit),
    @intFromEnum(Syscall.chroot),
    @intFromEnum(Syscall.fsync),
    @intFromEnum(Syscall.fdatasync),
    @intFromEnum(Syscall.getdents),
    @intFromEnum(Syscall.stat),
    @intFromEnum(Syscall.lstat),
    @intFromEnum(Syscall.statfs),
    @intFromEnum(Syscall.fcntl),
    @intFromEnum(Syscall.flock),
    @intFromEnum(Syscall.truncate),
    @intFromEnum(Syscall.ftruncate),
    @intFromEnum(Syscall.getpriority),
    @intFromEnum(Syscall.setpriority),
    @intFromEnum(Syscall.statx),
    @intFromEnum(Syscall.io_setup),
    @intFromEnum(Syscall.io_destroy),
    @intFromEnum(Syscall.io_getevents),
    @intFromEnum(Syscall.io_submit),
    @intFromEnum(Syscall.io_cancel),
    @intFromEnum(Syscall.epoll_create),
    @intFromEnum(Syscall.epoll_create1),
    @intFromEnum(Syscall.epoll_ctl),
    @intFromEnum(Syscall.epoll_wait),
    @intFromEnum(Syscall.epoll_pwait),
    @intFromEnum(Syscall.timer_create),
    @intFromEnum(Syscall.timer_settime),
    @intFromEnum(Syscall.timer_gettime),
    @intFromEnum(Syscall.timer_delete),
    @intFromEnum(Syscall.timerfd_create),
    @intFromEnum(Syscall.timerfd_settime),
    @intFromEnum(Syscall.timerfd_gettime),
    @intFromEnum(Syscall.eventfd),
    @intFromEnum(Syscall.eventfd2),
    @intFromEnum(Syscall.signalfd),
    @intFromEnum(Syscall.signalfd4),
    @intFromEnum(Syscall.ppoll),
    @intFromEnum(Syscall.inotify_init),
    @intFromEnum(Syscall.inotify_init1),
    @intFromEnum(Syscall.inotify_add_watch),
    @intFromEnum(Syscall.inotify_rm_watch),
    @intFromEnum(Syscall.tkill),
    @intFromEnum(Syscall.time),
    @intFromEnum(Syscall.futex),
    @intFromEnum(Syscall.sched_setaffinity),
    @intFromEnum(Syscall.sched_getaffinity),
    @intFromEnum(Syscall.prctl),
    @intFromEnum(Syscall.set_tid_address),
    @intFromEnum(Syscall.restart_syscall),
    @intFromEnum(Syscall.rt_sigaction),
    @intFromEnum(Syscall.rt_sigprocmask),
    @intFromEnum(Syscall.rt_sigreturn),
    @intFromEnum(Syscall.rt_sigpending),
    @intFromEnum(Syscall.rt_sigtimedwait),
    @intFromEnum(Syscall.rt_sigqueueinfo),
    @intFromEnum(Syscall.rt_sigsuspend),
    @intFromEnum(Syscall.sigaltstack),
    @intFromEnum(Syscall.mknod),
    @intFromEnum(Syscall.mknodat),
    @intFromEnum(Syscall.unlinkat),
    @intFromEnum(Syscall.mkdirat),
    @intFromEnum(Syscall.fchownat),
    @intFromEnum(Syscall.futimesat),
    @intFromEnum(Syscall.newfstatat),
    @intFromEnum(Syscall.renameat),
    @intFromEnum(Syscall.linkat),
    @intFromEnum(Syscall.symlinkat),
    @intFromEnum(Syscall.readlinkat),
    @intFromEnum(Syscall.fchmodat),
    @intFromEnum(Syscall.faccessat),
    @intFromEnum(Syscall.pselect6),
    @intFromEnum(Syscall.preadv),
    @intFromEnum(Syscall.pwritev),
    @intFromEnum(Syscall.utimensat),
    @intFromEnum(Syscall.epoll_wait),
    @intFromEnum(Syscall.ppoll),
    @intFromEnum(Syscall.perf_event_open),
    @intFromEnum(Syscall.syncfs),
    @intFromEnum(Syscall.setns),
    @intFromEnum(Syscall.getcpu),
};

pub fn enableStrictFilter() void {
    var filters = std.ArrayList(sock_filter).init(std.heap.page_allocator);
    defer filters.deinit();

    for (allowed_syscalls) |syscall| {
        filters.append(.{
            .code = 0x20,
            .jt = 0,
            .jf = 0,
            .k = @intCast(syscall),
        }) catch unreachable;
    }

    filters.append(.{
        .code = 0x06,
        .jt = 0,
        .jf = 0,
        .k = SECCOMP_RET_KILL,
    });

    const fprog: sock_fprog = .{
        .len = @intCast(filters.items.len),
        .filter = filters.items.ptr,
    };

    _ = linux.prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER, @intFromPtr(&fprog), 0, 0);
}
